import type { AssetDefinition } from "../types";

export const assetCatalog: Record<string, AssetDefinition> = {
  "character.oathbound.south": { contentId: "role.oathbound", path: "/assets/sprites/dungeon-roles-sheet.png", sheet: { columns: 4, rows: 3, index: 0 } },
  "character.oathbound.north": { contentId: "role.oathbound", path: "/assets/sprites/dungeon-roles-sheet.png", sheet: { columns: 4, rows: 3, index: 1 } },
  "character.oathbound.east": { contentId: "role.oathbound", path: "/assets/sprites/dungeon-roles-sheet.png", sheet: { columns: 4, rows: 3, index: 2 } },
  "character.oathbound.west": { contentId: "role.oathbound", path: "/assets/sprites/dungeon-roles-sheet.png", sheet: { columns: 4, rows: 3, index: 3 } },
  "character.ash-scout.south": { contentId: "role.ash-scout", path: "/assets/sprites/dungeon-roles-sheet.png", sheet: { columns: 4, rows: 3, index: 4 } },
  "character.ash-scout.north": { contentId: "role.ash-scout", path: "/assets/sprites/dungeon-roles-sheet.png", sheet: { columns: 4, rows: 3, index: 5 } },
  "character.ash-scout.east": { contentId: "role.ash-scout", path: "/assets/sprites/dungeon-roles-sheet.png", sheet: { columns: 4, rows: 3, index: 6 } },
  "character.ash-scout.west": { contentId: "role.ash-scout", path: "/assets/sprites/dungeon-roles-sheet.png", sheet: { columns: 4, rows: 3, index: 7 } },
  "character.lantern-priest.south": { contentId: "role.lantern-priest", path: "/assets/sprites/dungeon-roles-sheet.png", sheet: { columns: 4, rows: 3, index: 8 } },
  "character.lantern-priest.north": { contentId: "role.lantern-priest", path: "/assets/sprites/dungeon-roles-sheet.png", sheet: { columns: 4, rows: 3, index: 9 } },
  "character.lantern-priest.east": { contentId: "role.lantern-priest", path: "/assets/sprites/dungeon-roles-sheet.png", sheet: { columns: 4, rows: 3, index: 10 } },
  "character.lantern-priest.west": { contentId: "role.lantern-priest", path: "/assets/sprites/dungeon-roles-sheet.png", sheet: { columns: 4, rows: 3, index: 11 } },
  "event.blood-inscription": { contentId: "event.blood-inscription", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 13 } },
  "monster.ash-rat": { contentId: "monster.ash-rat", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 1 } },
  "monster.bone-thrall": { contentId: "monster.bone-thrall", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 2 } },
  "monster.cinder-cultist": { contentId: "monster.cinder-cultist", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 3 } },
  "item.rusted-sword": { contentId: "item.rusted-sword", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 8 } },
  "item.ember-tonic": { contentId: "item.ember-tonic", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 10 } },
  "monster.venom-bat": { contentId: "monster.venom-bat", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 4 } },
  "monster.shadow-imp": { contentId: "monster.shadow-imp", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 5 } },
  "monster.moss-brute": { contentId: "monster.moss-brute", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 6 } },
  "monster.blackstone-sentinel": { contentId: "monster.blackstone-sentinel", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 7 } },
  "item.iron-axe": { contentId: "item.iron-axe", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 9 } },
  "item.hunter-spear": { contentId: "item.hunter-spear", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 9 } },
  "item.greater-tonic": { contentId: "item.greater-tonic", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 11 } },
  "item.ward-shield": { contentId: "item.ward-shield", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 12 } },
  "item.leather-armor": { contentId: "item.leather-armor", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 15 } },
  "item.chain-mail": { contentId: "item.chain-mail", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 15 } },
  "item.trapweave-cloak": { contentId: "item.trapweave-cloak", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 15 } },
  "item.tower-kite-shield": { contentId: "item.tower-kite-shield", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 12 } },
  "item.silvered-mace": { contentId: "item.silvered-mace", path: "/assets/sprites/dungeon-advanced-sheet.png", sheet: { columns: 2, rows: 2, index: 0 } },
  "item.mapping-scroll": { contentId: "item.mapping-scroll", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 13 } },
  "item.ember-dart": { contentId: "item.ember-dart", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 13 } },
  "item.coin-pouch": { contentId: "item.coin-pouch", path: "/assets/sprites/dungeon-entities-sheet.png", sheet: { columns: 4, rows: 4, index: 14 } },
  "monster.ember-moth": { contentId: "monster.ember-moth", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 0 } },
  "monster.blackshield-grub": { contentId: "monster.blackshield-grub", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 1 } },
  "monster.hollow-archer": { contentId: "monster.hollow-archer", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 2 } },
  "monster.grave-leech": { contentId: "monster.grave-leech", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 3 } },
  "monster.bramble-packling": { contentId: "monster.bramble-packling", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 4 } },
  "monster.ash-warlock": { contentId: "monster.ash-warlock", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 5 } },
  "monster.iron-reliquary-guard": { contentId: "monster.iron-reliquary-guard", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 6 } },
  "item.oath-knife": { contentId: "item.oath-knife", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 7 } },
  "item.guardian-draught": { contentId: "item.guardian-draught", path: "/assets/sprites/dungeon-guardian-draught-sheet.png", sheet: { columns: 2, rows: 2, index: 0 } },
  "item.repulsion-scroll": { contentId: "item.repulsion-scroll", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 8 } },
  "item.glim-map": { contentId: "item.glim-map", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 9 } },
  "item.bloodmoss-salve": { contentId: "item.bloodmoss-salve", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 10 } },
  "item.unmarked-vial": { contentId: "item.unmarked-vial", path: "/assets/sprites/dungeon-guardian-draught-sheet.png", sheet: { columns: 2, rows: 2, index: 1 } },
  "item.sealed-prayer-strip": { contentId: "item.sealed-prayer-strip", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 13 } },
  "event.mend-shrine": { contentId: "event.mend-shrine", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 11 } },
  "event.cursed-coffer": { contentId: "event.cursed-coffer", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 12 } },
  "event.warning-brazier": { contentId: "event.warning-brazier", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 13 } },
  "event.broken-armory": { contentId: "event.broken-armory", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 14 } },
  "event.oath-echo": { contentId: "event.oath-echo", path: "/assets/sprites/dungeon-advanced-sheet.png", sheet: { columns: 2, rows: 2, index: 3 } },
  "event.scout-cache": { contentId: "event.scout-cache", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 13 } },
  "event.lantern-font": { contentId: "event.lantern-font", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 11 } },
  "event.dread-altar": { contentId: "event.dread-altar", path: "/assets/sprites/dungeon-expansion-sheet.png", sheet: { columns: 4, rows: 4, index: 11 } },
  "item.sun-sigil-blade": { contentId: "item.sun-sigil-blade", path: "/assets/sprites/dungeon-advanced-sheet.png", sheet: { columns: 2, rows: 2, index: 0 } },
  "item.moonlit-mail": { contentId: "item.moonlit-mail", path: "/assets/sprites/dungeon-advanced-sheet.png", sheet: { columns: 2, rows: 2, index: 1 } },
  "event.wayfarer-merchant": { contentId: "event.wayfarer-merchant", path: "/assets/sprites/dungeon-advanced-sheet.png", sheet: { columns: 2, rows: 2, index: 2 } },
  "event.furnace-control-stone": { contentId: "event.furnace-control-stone", path: "/assets/sprites/dungeon-advanced-sheet.png", sheet: { columns: 2, rows: 2, index: 3 } },
  "event.seal-key": { contentId: "event.seal-key", path: "/assets/sprites/dungeon-advanced-sheet.png", sheet: { columns: 2, rows: 2, index: 3 } },
  "item.void-prism": { contentId: "item.void-prism", path: "/assets/sprites/dungeon-advanced-sheet.png", sheet: { columns: 2, rows: 2, index: 3 } },
  "event.sealed-room": { contentId: "event.sealed-room", path: "/assets/sprites/dungeon-room-events-sheet.png", sheet: { columns: 3, rows: 1, index: 0 } },
  "event.dead-feast": { contentId: "event.dead-feast", path: "/assets/sprites/dungeon-room-events-sheet.png", sheet: { columns: 3, rows: 1, index: 1 } },
  "event.treasure-vault": { contentId: "event.treasure-vault", path: "/assets/sprites/dungeon-room-events-sheet.png", sheet: { columns: 3, rows: 1, index: 2 } },
  "event.candle-gallery": { contentId: "event.candle-gallery", path: "/assets/sprites/dungeon-room-events-sheet.png", sheet: { columns: 3, rows: 1, index: 0 } },
  "event.bone-heap": { contentId: "event.bone-heap", path: "/assets/sprites/dungeon-room-events-sheet.png", sheet: { columns: 3, rows: 1, index: 1 } },
  "event.furnace-chamber": { contentId: "event.furnace-chamber", path: "/assets/sprites/dungeon-room-events-sheet.png", sheet: { columns: 3, rows: 1, index: 2 } },
  "monster.crypt-priest": { contentId: "monster.crypt-priest", path: "/assets/sprites/dungeon-bosses-sheet.png", sheet: { columns: 3, rows: 2, index: 0 } },
  "monster.blackstone-colossus": { contentId: "monster.blackstone-colossus", path: "/assets/sprites/dungeon-bosses-sheet.png", sheet: { columns: 3, rows: 2, index: 1 } },
  "monster.black-candle-warden": { contentId: "monster.black-candle-warden", path: "/assets/sprites/dungeon-bosses-sheet.png", sheet: { columns: 3, rows: 2, index: 2 } },
  "item.grave-sun-charm": { contentId: "item.grave-sun-charm", path: "/assets/sprites/dungeon-bosses-sheet.png", sheet: { columns: 3, rows: 2, index: 3 } },
  "item.colossus-heart": { contentId: "item.colossus-heart", path: "/assets/sprites/dungeon-bosses-sheet.png", sheet: { columns: 3, rows: 2, index: 4 } },
  "item.black-candle-core": { contentId: "item.black-candle-core", path: "/assets/sprites/dungeon-bosses-sheet.png", sheet: { columns: 3, rows: 2, index: 5 } },
};

export function assetIdForContent(contentId: string): string {
  return Object.entries(assetCatalog).find(([, asset]) => asset.contentId === contentId)?.[0] ?? "floor:blackstone";
}

export function assetForContent(contentId: string): AssetDefinition | null {
  return Object.values(assetCatalog).find((asset) => asset.contentId === contentId) ?? null;
}
