import type { AssetDefinition } from "../types";

export const assetCatalog: Record<string, AssetDefinition> = {
  "character.oathbound.default": {
    id: "character.oathbound.default",
    kind: "character",
    entityRefs: ["role.oathbound"],
    styleTags: ["hero", "knight", "shield", "dark-fantasy"],
    size: 64,
    path: "/assets/sprites/dungeon-roles-sheet.png",
    sheet: { columns: 3, rows: 1, index: 0 },
    promptSeed: "64x64 top-down dark fantasy armored oathbound delver with sword, small shield, amber lantern, transparent background",
    status: "final",
  },
  "character.ash-scout.generated": {
    id: "character.ash-scout.generated",
    kind: "character",
    entityRefs: ["role.ash-scout"],
    styleTags: ["hero", "scout", "spear", "dark-fantasy"],
    size: 64,
    path: "/assets/sprites/dungeon-roles-sheet.png",
    sheet: { columns: 3, rows: 1, index: 1 },
    promptSeed: "64x64 top-down dark fantasy ash cloaked scout with spear, transparent background",
    status: "final",
  },
  "character.lantern-priest.generated": {
    id: "character.lantern-priest.generated",
    kind: "character",
    entityRefs: ["role.lantern-priest"],
    styleTags: ["hero", "priest", "lantern", "dark-fantasy"],
    size: 64,
    path: "/assets/sprites/dungeon-roles-sheet.png",
    sheet: { columns: 3, rows: 1, index: 2 },
    promptSeed: "64x64 top-down dark fantasy lantern priest with staff and warm light, transparent background",
    status: "final",
  },
  "terrain.floor.stone.default": {
    id: "terrain.floor.stone.default",
    kind: "terrain",
    entityRefs: ["terrain.floor.stone"],
    styleTags: ["stone", "floor", "dungeon"],
    size: 64,
    path: "/assets/sprites/dungeon-terrain-sheet.png",
    sheet: { columns: 4, rows: 2, index: 0 },
    promptSeed: "64x64 seamless top-down cracked black stone dungeon floor, low contrast, dark fantasy",
    status: "generated",
  },
  "terrain.wall.blackstone.default": {
    id: "terrain.wall.blackstone.default",
    kind: "terrain",
    entityRefs: ["terrain.wall.blackstone"],
    styleTags: ["blackstone", "wall", "engraved"],
    size: 64,
    path: "/assets/sprites/dungeon-terrain-sheet.png",
    sheet: { columns: 4, rows: 2, index: 2 },
    promptSeed: "64x64 top-down blackstone dungeon wall block, ancient engraving, dark fantasy, readable edge",
    status: "generated",
  },
  "terrain.stairs.down.default": {
    id: "terrain.stairs.down.default",
    kind: "terrain",
    entityRefs: ["terrain.stairs.down"],
    styleTags: ["stairs", "goal", "amber-light"],
    size: 64,
    path: "/assets/sprites/dungeon-terrain-sheet.png",
    sheet: { columns: 4, rows: 2, index: 4 },
    promptSeed: "64x64 top-down descending stone stairs, faint amber rim light, dark fantasy dungeon",
    status: "generated",
  },
  "terrain.floor.blackstone.biome": {
    id: "terrain.floor.blackstone.biome",
    kind: "terrain",
    entityRefs: ["terrain.floor.stone"],
    styleTags: ["stone", "blackstone", "floor", "biome"],
    size: 64,
    path: "/assets/sprites/dungeon-biomes-sheet.png",
    sheet: { columns: 4, rows: 2, index: 0 },
    promptSeed: "64x64 seamless top-down blackstone dungeon floor tile, dark fantasy, low contrast",
    status: "final",
  },
  "terrain.floor.crypt.biome": {
    id: "terrain.floor.crypt.biome",
    kind: "terrain",
    entityRefs: ["terrain.floor.crypt"],
    styleTags: ["crypt", "bone", "floor", "biome"],
    size: 64,
    path: "/assets/sprites/dungeon-biomes-sheet.png",
    sheet: { columns: 4, rows: 2, index: 1 },
    promptSeed: "64x64 seamless top-down dark fantasy crypt floor with faint bone dust, low contrast",
    status: "final",
  },
  "terrain.floor.furnace.biome": {
    id: "terrain.floor.furnace.biome",
    kind: "terrain",
    entityRefs: ["terrain.floor.furnace"],
    styleTags: ["furnace", "ember", "floor", "biome"],
    size: 64,
    path: "/assets/sprites/dungeon-biomes-sheet.png",
    sheet: { columns: 4, rows: 2, index: 2 },
    promptSeed: "64x64 seamless top-down dark fantasy furnace ruin floor with ember cracks, low contrast",
    status: "final",
  },
  "terrain.floor.black-candle.biome": {
    id: "terrain.floor.black-candle.biome",
    kind: "terrain",
    entityRefs: ["terrain.floor.black-candle"],
    styleTags: ["black-candle", "ritual", "floor", "biome"],
    size: 64,
    path: "/assets/sprites/dungeon-biomes-sheet.png",
    sheet: { columns: 4, rows: 2, index: 3 },
    promptSeed: "64x64 seamless top-down dark fantasy black candle sanctum floor with ritual soot, low contrast",
    status: "final",
  },
  "terrain.wall.blackstone.biome": {
    id: "terrain.wall.blackstone.biome",
    kind: "terrain",
    entityRefs: ["terrain.wall.blackstone"],
    styleTags: ["blackstone", "wall", "biome"],
    size: 64,
    path: "/assets/sprites/dungeon-biomes-sheet.png",
    sheet: { columns: 4, rows: 2, index: 4 },
    promptSeed: "64x64 top-down blackstone dungeon wall tile, dark fantasy, readable edge",
    status: "final",
  },
  "terrain.wall.crypt.biome": {
    id: "terrain.wall.crypt.biome",
    kind: "terrain",
    entityRefs: ["terrain.wall.crypt"],
    styleTags: ["crypt", "wall", "biome"],
    size: 64,
    path: "/assets/sprites/dungeon-biomes-sheet.png",
    sheet: { columns: 4, rows: 2, index: 5 },
    promptSeed: "64x64 top-down dark fantasy crypt wall tile with worn tomb stone, readable edge",
    status: "final",
  },
  "terrain.wall.furnace.biome": {
    id: "terrain.wall.furnace.biome",
    kind: "terrain",
    entityRefs: ["terrain.wall.furnace"],
    styleTags: ["furnace", "wall", "biome"],
    size: 64,
    path: "/assets/sprites/dungeon-biomes-sheet.png",
    sheet: { columns: 4, rows: 2, index: 6 },
    promptSeed: "64x64 top-down dark fantasy furnace ruin wall with ember seams, readable edge",
    status: "final",
  },
  "terrain.wall.black-candle.biome": {
    id: "terrain.wall.black-candle.biome",
    kind: "terrain",
    entityRefs: ["terrain.wall.black-candle"],
    styleTags: ["black-candle", "wall", "biome"],
    size: 64,
    path: "/assets/sprites/dungeon-biomes-sheet.png",
    sheet: { columns: 4, rows: 2, index: 7 },
    promptSeed: "64x64 top-down dark fantasy black candle sanctum wall tile, readable edge",
    status: "final",
  },
  "terrain.cover.blackstone.generated": {
    id: "terrain.cover.blackstone.generated",
    kind: "terrain",
    entityRefs: ["terrain.cover.blackstone"],
    styleTags: ["cover", "blackstone", "line-of-sight", "biome"],
    size: 64,
    path: "/assets/sprites/dungeon-cover-sheet.png",
    sheet: { columns: 4, rows: 1, index: 0 },
    promptSeed: "top-down dark fantasy blackstone broken pillar base, walkable cover terrain, readable at 64px",
    status: "generated",
  },
  "terrain.cover.crypt.generated": {
    id: "terrain.cover.crypt.generated",
    kind: "terrain",
    entityRefs: ["terrain.cover.crypt"],
    styleTags: ["cover", "crypt", "line-of-sight", "biome"],
    size: 64,
    path: "/assets/sprites/dungeon-cover-sheet.png",
    sheet: { columns: 4, rows: 1, index: 1 },
    promptSeed: "top-down dark fantasy crypt sarcophagus slab, walkable cover terrain, readable at 64px",
    status: "generated",
  },
  "terrain.cover.furnace.generated": {
    id: "terrain.cover.furnace.generated",
    kind: "terrain",
    entityRefs: ["terrain.cover.furnace"],
    styleTags: ["cover", "furnace", "line-of-sight", "biome"],
    size: 64,
    path: "/assets/sprites/dungeon-cover-sheet.png",
    sheet: { columns: 4, rows: 1, index: 2 },
    promptSeed: "top-down dark fantasy furnace ruin iron baffle with ember cracks, walkable cover terrain, readable at 64px",
    status: "generated",
  },
  "terrain.cover.black-candle.generated": {
    id: "terrain.cover.black-candle.generated",
    kind: "terrain",
    entityRefs: ["terrain.cover.black-candle"],
    styleTags: ["cover", "black-candle", "line-of-sight", "biome"],
    size: 64,
    path: "/assets/sprites/dungeon-cover-sheet.png",
    sheet: { columns: 4, rows: 1, index: 3 },
    promptSeed: "top-down dark fantasy black candle wax-covered ritual plinth, walkable cover terrain, readable at 64px",
    status: "generated",
  },
  "event.blood-inscription.default": {
    id: "event.blood-inscription.default",
    kind: "event",
    entityRefs: ["event.blood-inscription"],
    styleTags: ["event", "rune", "blood", "dungeon"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 13 },
    promptSeed: "64x64 top-down dark fantasy blood-written floor inscription, transparent background",
    status: "generated",
  },
  "monster.ash-rat.default": {
    id: "monster.ash-rat.default",
    kind: "monster",
    entityRefs: ["monster.ash-rat"],
    styleTags: ["beast", "skirmisher", "early"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 1 },
    promptSeed: "64x64 top-down ash-gray dungeon rat monster, red eyes, clean silhouette, transparent background",
    status: "generated",
  },
  "monster.bone-thrall.default": {
    id: "monster.bone-thrall.default",
    kind: "monster",
    entityRefs: ["monster.bone-thrall"],
    styleTags: ["undead", "melee", "early"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 2 },
    promptSeed: "64x64 top-down skeletal thrall with rusted blade, blue ember, dark fantasy, transparent background",
    status: "generated",
  },
  "monster.cinder-cultist.default": {
    id: "monster.cinder-cultist.default",
    kind: "monster",
    entityRefs: ["monster.cinder-cultist"],
    styleTags: ["cult", "caster", "early"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 3 },
    promptSeed: "64x64 top-down masked cinder cultist in robe, ember magic, dark fantasy, transparent background",
    status: "generated",
  },
  "item.rusted-sword.default": {
    id: "item.rusted-sword.default",
    kind: "item",
    entityRefs: ["item.rusted-sword"],
    styleTags: ["weapon", "loot", "early"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 8 },
    promptSeed: "64x64 top-down rusted short sword item icon, dark fantasy, transparent background",
    status: "generated",
  },
  "item.ember-tonic.default": {
    id: "item.ember-tonic.default",
    kind: "item",
    entityRefs: ["item.ember-tonic"],
    styleTags: ["potion", "healing", "loot"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 10 },
    promptSeed: "64x64 top-down red healing potion vial, warm ember glow, dark fantasy, transparent background",
    status: "generated",
  },
  "monster.venom-bat.default": {
    id: "monster.venom-bat.default",
    kind: "monster",
    entityRefs: ["monster.venom-bat"],
    styleTags: ["beast", "flying", "early"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 4 },
    promptSeed: "64x64 top-down dark fantasy venom bat, transparent background",
    status: "generated",
  },
  "monster.shadow-imp.default": {
    id: "monster.shadow-imp.default",
    kind: "monster",
    entityRefs: ["monster.shadow-imp"],
    styleTags: ["demon", "skirmisher", "mid"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 5 },
    promptSeed: "64x64 top-down dark fantasy shadow imp, transparent background",
    status: "generated",
  },
  "monster.moss-brute.default": {
    id: "monster.moss-brute.default",
    kind: "monster",
    entityRefs: ["monster.moss-brute"],
    styleTags: ["beast", "heavy", "mid"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 6 },
    promptSeed: "64x64 top-down dark fantasy moss brute, transparent background",
    status: "generated",
  },
  "monster.blackstone-sentinel.default": {
    id: "monster.blackstone-sentinel.default",
    kind: "monster",
    entityRefs: ["monster.blackstone-sentinel"],
    styleTags: ["construct", "elite", "late"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 7 },
    promptSeed: "64x64 top-down dark fantasy blackstone sentinel, transparent background",
    status: "generated",
  },
  "item.iron-axe.default": {
    id: "item.iron-axe.default",
    kind: "item",
    entityRefs: ["item.iron-axe"],
    styleTags: ["weapon", "axe", "loot"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 9 },
    promptSeed: "64x64 top-down dark fantasy iron battle axe, transparent background",
    status: "generated",
  },
  "item.hunter-spear.default": {
    id: "item.hunter-spear.default",
    kind: "item",
    entityRefs: ["item.hunter-spear"],
    styleTags: ["weapon", "spear", "loot"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 9 },
    promptSeed: "64x64 top-down dark fantasy hunter spear, transparent background",
    status: "generated",
  },
  "item.greater-tonic.default": {
    id: "item.greater-tonic.default",
    kind: "item",
    entityRefs: ["item.greater-tonic"],
    styleTags: ["potion", "healing", "loot"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 11 },
    promptSeed: "64x64 top-down dark fantasy greater crimson healing flask, transparent background",
    status: "generated",
  },
  "item.ward-shield.default": {
    id: "item.ward-shield.default",
    kind: "item",
    entityRefs: ["item.ward-shield"],
    styleTags: ["shield", "defense", "loot"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 12 },
    promptSeed: "64x64 top-down dark fantasy ward shield, transparent background",
    status: "generated",
  },
  "item.leather-armor.default": {
    id: "item.leather-armor.default",
    kind: "item",
    entityRefs: ["item.leather-armor"],
    styleTags: ["armor", "defense", "loot"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 15 },
    promptSeed: "64x64 top-down dark fantasy leather armor item icon, transparent background",
    status: "generated",
  },
  "item.chain-mail.default": {
    id: "item.chain-mail.default",
    kind: "item",
    entityRefs: ["item.chain-mail"],
    styleTags: ["armor", "chain-mail", "loot"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 15 },
    promptSeed: "64x64 top-down dark fantasy chain mail armor item icon, transparent background",
    status: "generated",
  },
  "item.trapweave-cloak.generated": {
    id: "item.trapweave-cloak.generated",
    kind: "item",
    entityRefs: ["item.trapweave-cloak"],
    styleTags: ["armor", "cloak", "trap"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 15 },
    promptSeed: "64x64 top-down dark fantasy dark cloak with tiny ward threads, transparent background",
    status: "generated",
  },
  "item.tower-kite-shield.generated": {
    id: "item.tower-kite-shield.generated",
    kind: "item",
    entityRefs: ["item.tower-kite-shield"],
    styleTags: ["shield", "ranged-defense", "heavy"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 12 },
    promptSeed: "64x64 top-down dark fantasy tall kite shield with black candle scars, transparent background",
    status: "generated",
  },
  "item.silvered-mace.generated": {
    id: "item.silvered-mace.generated",
    kind: "item",
    entityRefs: ["item.silvered-mace"],
    styleTags: ["weapon", "mace", "silver"],
    size: 64,
    path: "/assets/sprites/dungeon-advanced-sheet.png",
    sheet: { columns: 2, rows: 2, index: 0 },
    promptSeed: "64x64 top-down dark fantasy silvered mace weapon icon, transparent background",
    status: "generated",
  },
  "item.mapping-scroll.default": {
    id: "item.mapping-scroll.default",
    kind: "item",
    entityRefs: ["item.mapping-scroll"],
    styleTags: ["scroll", "map", "loot"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 13 },
    promptSeed: "64x64 top-down dark fantasy map scroll, transparent background",
    status: "generated",
  },
  "item.ember-dart.default": {
    id: "item.ember-dart.default",
    kind: "item",
    entityRefs: ["item.ember-dart"],
    styleTags: ["throwing", "dart", "ember", "loot"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 13 },
    promptSeed: "64x64 top-down dark fantasy ember throwing dart item icon, transparent background",
    status: "generated",
  },
  "item.coin-pouch.default": {
    id: "item.coin-pouch.default",
    kind: "item",
    entityRefs: ["item.coin-pouch"],
    styleTags: ["treasure", "loot"],
    size: 64,
    path: "/assets/sprites/dungeon-entities-sheet.png",
    sheet: { columns: 4, rows: 4, index: 14 },
    promptSeed: "64x64 top-down dark fantasy coin pouch, transparent background",
    status: "generated",
  },
  "monster.ember-moth.generated": {
    id: "monster.ember-moth.generated",
    kind: "monster",
    entityRefs: ["monster.ember-moth"],
    styleTags: ["beast", "flying", "ember", "early"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 0 },
    promptSeed: "64x64 top-down dark fantasy ember moth monster, transparent background",
    status: "final",
  },
  "monster.blackshield-grub.generated": {
    id: "monster.blackshield-grub.generated",
    kind: "monster",
    entityRefs: ["monster.blackshield-grub"],
    styleTags: ["beast", "durable", "armored"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 1 },
    promptSeed: "64x64 top-down dark fantasy blackshield grub, transparent background",
    status: "final",
  },
  "monster.hollow-archer.generated": {
    id: "monster.hollow-archer.generated",
    kind: "monster",
    entityRefs: ["monster.hollow-archer"],
    styleTags: ["undead", "ranged", "archer"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 2 },
    promptSeed: "64x64 top-down dark fantasy hollow undead archer, transparent background",
    status: "final",
  },
  "monster.grave-leech.generated": {
    id: "monster.grave-leech.generated",
    kind: "monster",
    entityRefs: ["monster.grave-leech"],
    styleTags: ["beast", "bleed", "crawler"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 3 },
    promptSeed: "64x64 top-down dark fantasy grave leech monster, transparent background",
    status: "final",
  },
  "monster.bramble-packling.generated": {
    id: "monster.bramble-packling.generated",
    kind: "monster",
    entityRefs: ["monster.bramble-packling"],
    styleTags: ["beast", "pack", "bramble"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 4 },
    promptSeed: "64x64 top-down dark fantasy bramble pack beast, transparent background",
    status: "final",
  },
  "monster.ash-warlock.generated": {
    id: "monster.ash-warlock.generated",
    kind: "monster",
    entityRefs: ["monster.ash-warlock"],
    styleTags: ["cult", "caster", "ash"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 5 },
    promptSeed: "64x64 top-down dark fantasy ash warlock, transparent background",
    status: "final",
  },
  "monster.iron-reliquary-guard.generated": {
    id: "monster.iron-reliquary-guard.generated",
    kind: "monster",
    entityRefs: ["monster.iron-reliquary-guard"],
    styleTags: ["construct", "elite", "reliquary"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 6 },
    promptSeed: "64x64 top-down dark fantasy iron reliquary guard, transparent background",
    status: "final",
  },
  "item.oath-knife.generated": {
    id: "item.oath-knife.generated",
    kind: "item",
    entityRefs: ["item.oath-knife"],
    styleTags: ["weapon", "knife", "loot"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 7 },
    promptSeed: "64x64 top-down dark fantasy oath knife, transparent background",
    status: "final",
  },
  "item.guardian-draught.generated": {
    id: "item.guardian-draught.generated",
    kind: "item",
    entityRefs: ["item.guardian-draught"],
    styleTags: ["potion", "defense", "blue"],
    size: 64,
    path: "/assets/sprites/dungeon-guardian-draught-sheet.png",
    sheet: { columns: 2, rows: 2, index: 0 },
    promptSeed: "64x64 top-down dark fantasy blue guardian draught with shield glow, transparent background",
    status: "final",
  },
  "item.repulsion-scroll.generated": {
    id: "item.repulsion-scroll.generated",
    kind: "item",
    entityRefs: ["item.repulsion-scroll"],
    styleTags: ["scroll", "control", "wind"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 8 },
    promptSeed: "64x64 top-down dark fantasy repulsion scroll, transparent background",
    status: "final",
  },
  "item.glim-map.generated": {
    id: "item.glim-map.generated",
    kind: "item",
    entityRefs: ["item.glim-map"],
    styleTags: ["map", "utility", "glow"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 9 },
    promptSeed: "64x64 top-down dark fantasy glowing folded map, transparent background",
    status: "final",
  },
  "item.bloodmoss-salve.generated": {
    id: "item.bloodmoss-salve.generated",
    kind: "item",
    entityRefs: ["item.bloodmoss-salve"],
    styleTags: ["salve", "cure", "loot"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 10 },
    promptSeed: "64x64 top-down dark fantasy bloodmoss salve jar, transparent background",
    status: "final",
  },
  "item.unmarked-vial.generated": {
    id: "item.unmarked-vial.generated",
    kind: "item",
    entityRefs: ["item.unmarked-vial"],
    styleTags: ["potion", "mystery", "unknown"],
    size: 64,
    path: "/assets/sprites/dungeon-guardian-draught-sheet.png",
    sheet: { columns: 2, rows: 2, index: 1 },
    promptSeed: "64x64 top-down dark fantasy unmarked black glass vial with faint amber seal, transparent background",
    status: "generated",
  },
  "item.sealed-prayer-strip.generated": {
    id: "item.sealed-prayer-strip.generated",
    kind: "item",
    entityRefs: ["item.sealed-prayer-strip"],
    styleTags: ["scroll", "mystery", "prayer"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 13 },
    promptSeed: "64x64 top-down dark fantasy sealed prayer paper strip with wax mark, transparent background",
    status: "generated",
  },
  "event.mend-shrine.generated": {
    id: "event.mend-shrine.generated",
    kind: "event",
    entityRefs: ["event.mend-shrine"],
    styleTags: ["event", "shrine", "healing"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 11 },
    promptSeed: "64x64 top-down dark fantasy healing shrine, transparent background",
    status: "final",
  },
  "event.cursed-coffer.generated": {
    id: "event.cursed-coffer.generated",
    kind: "event",
    entityRefs: ["event.cursed-coffer"],
    styleTags: ["event", "treasure", "curse"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 12 },
    promptSeed: "64x64 top-down dark fantasy cursed coffer, transparent background",
    status: "final",
  },
  "event.warning-brazier.generated": {
    id: "event.warning-brazier.generated",
    kind: "event",
    entityRefs: ["event.warning-brazier"],
    styleTags: ["event", "brazier", "warning"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 13 },
    promptSeed: "64x64 top-down dark fantasy warning brazier, transparent background",
    status: "final",
  },
  "event.broken-armory.generated": {
    id: "event.broken-armory.generated",
    kind: "event",
    entityRefs: ["event.broken-armory"],
    styleTags: ["event", "weapon", "armory"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 14 },
    promptSeed: "64x64 top-down dark fantasy broken weapon rack, transparent background",
    status: "final",
  },
  "event.oath-echo.generated": {
    id: "event.oath-echo.generated",
    kind: "event",
    entityRefs: ["event.oath-echo"],
    styleTags: ["event", "role", "oathbound"],
    size: 64,
    path: "/assets/sprites/dungeon-advanced-sheet.png",
    sheet: { columns: 2, rows: 2, index: 3 },
    promptSeed: "64x64 top-down dark fantasy blackstone oath rune marker, transparent background",
    status: "generated",
  },
  "event.scout-cache.generated": {
    id: "event.scout-cache.generated",
    kind: "event",
    entityRefs: ["event.scout-cache"],
    styleTags: ["event", "role", "scout"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 13 },
    promptSeed: "64x64 top-down dark fantasy ash scout cache mark on floor, transparent background",
    status: "generated",
  },
  "event.lantern-font.generated": {
    id: "event.lantern-font.generated",
    kind: "event",
    entityRefs: ["event.lantern-font"],
    styleTags: ["event", "role", "priest"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 11 },
    promptSeed: "64x64 top-down dark fantasy lantern-lit cleansing font, transparent background",
    status: "generated",
  },
  "event.dread-altar.generated": {
    id: "event.dread-altar.generated",
    kind: "event",
    entityRefs: ["event.dread-altar"],
    styleTags: ["event", "altar", "trap-reveal"],
    size: 64,
    path: "/assets/sprites/dungeon-expansion-sheet.png",
    sheet: { columns: 4, rows: 4, index: 11 },
    promptSeed: "64x64 top-down dark fantasy blood altar marker, transparent background",
    status: "generated",
  },
  "item.sun-sigil-blade.generated": {
    id: "item.sun-sigil-blade.generated",
    kind: "item",
    entityRefs: ["item.sun-sigil-blade"],
    styleTags: ["weapon", "sun", "special"],
    size: 64,
    path: "/assets/sprites/dungeon-advanced-sheet.png",
    sheet: { columns: 2, rows: 2, index: 0 },
    promptSeed: "64x64 top-down dark fantasy sun sigil blade, transparent background",
    status: "final",
  },
  "item.moonlit-mail.generated": {
    id: "item.moonlit-mail.generated",
    kind: "item",
    entityRefs: ["item.moonlit-mail"],
    styleTags: ["armor", "moon", "special"],
    size: 64,
    path: "/assets/sprites/dungeon-advanced-sheet.png",
    sheet: { columns: 2, rows: 2, index: 1 },
    promptSeed: "64x64 top-down dark fantasy moonlit mail armor, transparent background",
    status: "final",
  },
  "event.wayfarer-merchant.generated": {
    id: "event.wayfarer-merchant.generated",
    kind: "event",
    entityRefs: ["event.wayfarer-merchant"],
    styleTags: ["merchant", "gold", "service"],
    size: 64,
    path: "/assets/sprites/dungeon-advanced-sheet.png",
    sheet: { columns: 2, rows: 2, index: 2 },
    promptSeed: "64x64 top-down dark fantasy wayfarer merchant with lantern, transparent background",
    status: "final",
  },
  "event.furnace-control-stone.generated": {
    id: "event.furnace-control-stone.generated",
    kind: "event",
    entityRefs: ["event.furnace-control-stone"],
    styleTags: ["event", "furnace", "obelisk"],
    size: 64,
    path: "/assets/sprites/dungeon-advanced-sheet.png",
    sheet: { columns: 2, rows: 2, index: 3 },
    promptSeed: "64x64 top-down dark fantasy ember control obelisk, transparent background",
    status: "generated",
  },
  "event.seal-key.generated": {
    id: "event.seal-key.generated",
    kind: "event",
    entityRefs: ["event.seal-key"],
    styleTags: ["event", "key", "boss-reward"],
    size: 64,
    path: "/assets/sprites/dungeon-advanced-sheet.png",
    sheet: { columns: 2, rows: 2, index: 3 },
    promptSeed: "64x64 top-down dark fantasy sealed key relic, transparent background",
    status: "generated",
  },
  "item.void-prism.generated": {
    id: "item.void-prism.generated",
    kind: "item",
    entityRefs: ["item.void-prism"],
    styleTags: ["relic", "void", "control"],
    size: 64,
    path: "/assets/sprites/dungeon-advanced-sheet.png",
    sheet: { columns: 2, rows: 2, index: 3 },
    promptSeed: "64x64 top-down dark fantasy void prism charm, transparent background",
    status: "final",
  },
  "trap.blood-needle.generated": {
    id: "trap.blood-needle.generated",
    kind: "trap",
    entityRefs: ["trap.blood-needle"],
    styleTags: ["trap", "bleed", "needle"],
    size: 64,
    path: "/assets/sprites/dungeon-traps-sheet.png",
    sheet: { columns: 3, rows: 1, index: 0 },
    promptSeed: "64x64 top-down dark fantasy blood needle floor trap, transparent background",
    status: "final",
  },
  "trap.risk-panel.generated": {
    id: "trap.risk-panel.generated",
    kind: "trap",
    entityRefs: ["trap.risk-panel"],
    styleTags: ["trap", "risk-reward", "question-sigil"],
    size: 64,
    path: "/assets/sprites/fate-sigil-tile.png",
    promptSeed: "64x64 top-down dark fantasy glowing question sigil carved into dark stone floor, readable mystery marker",
    status: "final",
  },
  "trap.venom-mist.generated": {
    id: "trap.venom-mist.generated",
    kind: "trap",
    entityRefs: ["trap.venom-mist"],
    styleTags: ["trap", "poison", "mist"],
    size: 64,
    path: "/assets/sprites/dungeon-traps-sheet.png",
    sheet: { columns: 3, rows: 1, index: 1 },
    promptSeed: "64x64 top-down dark fantasy venom mist floor trap, transparent background",
    status: "final",
  },
  "trap.crumbling-floor.generated": {
    id: "trap.crumbling-floor.generated",
    kind: "trap",
    entityRefs: ["trap.crumbling-floor"],
    styleTags: ["trap", "collapse", "cracked-floor"],
    size: 64,
    path: "/assets/sprites/dungeon-traps-sheet.png",
    sheet: { columns: 3, rows: 1, index: 2 },
    promptSeed: "64x64 top-down dark fantasy crumbling floor trap, transparent background",
    status: "final",
  },
  "event.sealed-room.generated": {
    id: "event.sealed-room.generated",
    kind: "event",
    entityRefs: ["event.sealed-room"],
    styleTags: ["event", "room", "sealed"],
    size: 64,
    path: "/assets/sprites/dungeon-room-events-sheet.png",
    sheet: { columns: 3, rows: 1, index: 0 },
    promptSeed: "64x64 top-down dark fantasy sealed room marker with runic lock, transparent background",
    status: "final",
  },
  "event.dead-feast.generated": {
    id: "event.dead-feast.generated",
    kind: "event",
    entityRefs: ["event.dead-feast"],
    styleTags: ["event", "room", "undead"],
    size: 64,
    path: "/assets/sprites/dungeon-room-events-sheet.png",
    sheet: { columns: 3, rows: 1, index: 1 },
    promptSeed: "64x64 top-down dark fantasy dead feast room marker, transparent background",
    status: "final",
  },
  "event.treasure-vault.generated": {
    id: "event.treasure-vault.generated",
    kind: "event",
    entityRefs: ["event.treasure-vault"],
    styleTags: ["event", "room", "treasure"],
    size: 64,
    path: "/assets/sprites/dungeon-room-events-sheet.png",
    sheet: { columns: 3, rows: 1, index: 2 },
    promptSeed: "64x64 top-down dark fantasy treasure vault marker, transparent background",
    status: "final",
  },
  "event.candle-gallery.generated": {
    id: "event.candle-gallery.generated",
    kind: "event",
    entityRefs: ["event.candle-gallery"],
    styleTags: ["event", "room", "candle"],
    size: 64,
    path: "/assets/sprites/dungeon-room-events-sheet.png",
    sheet: { columns: 3, rows: 1, index: 0 },
    promptSeed: "64x64 top-down dark fantasy candle gallery room marker, transparent background",
    status: "generated",
  },
  "event.bone-heap.generated": {
    id: "event.bone-heap.generated",
    kind: "event",
    entityRefs: ["event.bone-heap"],
    styleTags: ["event", "room", "bone"],
    size: 64,
    path: "/assets/sprites/dungeon-room-events-sheet.png",
    sheet: { columns: 3, rows: 1, index: 1 },
    promptSeed: "64x64 top-down dark fantasy bone heap room marker with buried supplies, transparent background",
    status: "generated",
  },
  "event.furnace-chamber.generated": {
    id: "event.furnace-chamber.generated",
    kind: "event",
    entityRefs: ["event.furnace-chamber"],
    styleTags: ["event", "room", "furnace"],
    size: 64,
    path: "/assets/sprites/dungeon-room-events-sheet.png",
    sheet: { columns: 3, rows: 1, index: 2 },
    promptSeed: "64x64 top-down dark fantasy furnace chamber room marker with ember iron plates, transparent background",
    status: "generated",
  },
  "monster.crypt-priest.generated": {
    id: "monster.crypt-priest.generated",
    kind: "monster",
    entityRefs: ["monster.crypt-priest"],
    styleTags: ["boss", "undead", "crypt"],
    size: 64,
    path: "/assets/sprites/dungeon-bosses-sheet.png",
    sheet: { columns: 3, rows: 2, index: 0 },
    promptSeed: "64x64 top-down dark fantasy crypt priest boss with bone mask, transparent background",
    status: "final",
  },
  "monster.blackstone-colossus.generated": {
    id: "monster.blackstone-colossus.generated",
    kind: "monster",
    entityRefs: ["monster.blackstone-colossus"],
    styleTags: ["boss", "construct", "blackstone"],
    size: 64,
    path: "/assets/sprites/dungeon-bosses-sheet.png",
    sheet: { columns: 3, rows: 2, index: 1 },
    promptSeed: "64x64 top-down dark fantasy blackstone colossus boss with ember core, transparent background",
    status: "final",
  },
  "monster.black-candle-warden.generated": {
    id: "monster.black-candle-warden.generated",
    kind: "monster",
    entityRefs: ["monster.black-candle-warden"],
    styleTags: ["boss", "demon", "black-candle"],
    size: 64,
    path: "/assets/sprites/dungeon-bosses-sheet.png",
    sheet: { columns: 3, rows: 2, index: 2 },
    promptSeed: "64x64 top-down dark fantasy black candle warden final boss, transparent background",
    status: "final",
  },
  "item.grave-sun-charm.generated": {
    id: "item.grave-sun-charm.generated",
    kind: "item",
    entityRefs: ["item.grave-sun-charm"],
    styleTags: ["relic", "boss-reward", "cure"],
    size: 64,
    path: "/assets/sprites/dungeon-bosses-sheet.png",
    sheet: { columns: 3, rows: 2, index: 3 },
    promptSeed: "64x64 top-down dark fantasy grave sun charm relic, transparent background",
    status: "final",
  },
  "item.colossus-heart.generated": {
    id: "item.colossus-heart.generated",
    kind: "item",
    entityRefs: ["item.colossus-heart"],
    styleTags: ["relic", "boss-reward", "ember-core"],
    size: 64,
    path: "/assets/sprites/dungeon-bosses-sheet.png",
    sheet: { columns: 3, rows: 2, index: 4 },
    promptSeed: "64x64 top-down dark fantasy colossus heart shard relic, transparent background",
    status: "final",
  },
  "item.black-candle-core.generated": {
    id: "item.black-candle-core.generated",
    kind: "item",
    entityRefs: ["item.black-candle-core"],
    styleTags: ["relic", "boss-reward", "black-candle"],
    size: 64,
    path: "/assets/sprites/dungeon-bosses-sheet.png",
    sheet: { columns: 3, rows: 2, index: 5 },
    promptSeed: "64x64 top-down dark fantasy black candle core relic, transparent background",
    status: "final",
  },
};

export function assetIdForContent(contentId: string): string {
  const match = Object.values(assetCatalog).find((asset) => asset.entityRefs.includes(contentId));
  return match?.id ?? "terrain.floor.stone.default";
}

export function assetForContent(contentId: string): AssetDefinition | null {
  return Object.values(assetCatalog).find((asset) => asset.entityRefs.includes(contentId)) ?? null;
}
