import { expansionEntities } from "./expansionEntities";
import type { ContentEntity } from "../types";

export const contentEntities: Record<string, ContentEntity> = {
  ...expansionEntities,
  "role.oathbound": { name: "ナイト", tier: "early" },
  "role.ash-scout": { name: "レンジャー", tier: "early" },
  "role.lantern-priest": { name: "プリースト", tier: "early" },
  "event.blood-inscription": { name: "血文字の石碑", tier: "early" },
  "monster.ash-rat": { name: "大ネズミ", tier: "early", danger: 2, xpReward: 4, family: "beast" },
  "monster.bone-thrall": { name: "スケルトン", tier: "early", danger: 4, xpReward: 7, family: "undead" },
  "monster.cinder-cultist": { name: "邪教徒", tier: "early", danger: 6, xpReward: 10, family: "cult" },
  "monster.venom-bat": { name: "毒コウモリ", tier: "early", danger: 3, xpReward: 5, family: "beast" },
  "monster.shadow-imp": { name: "インプ", tier: "mid", danger: 5, xpReward: 10, family: "demon" },
  "monster.moss-brute": { name: "苔のトロル", tier: "mid", danger: 7, xpReward: 14, family: "beast" },
  "monster.blackstone-sentinel": { name: "ストーンゴーレム", tier: "late", danger: 9, xpReward: 20, family: "construct" },
  "item.rusted-sword": { name: "錆びたショートソード", tier: "early", economyValue: 5 },
  "item.ember-tonic": { name: "回復薬", tier: "early", economyValue: 20 },
  "item.iron-axe": { name: "バトルアックス", tier: "mid", economyValue: 55 },
  "item.hunter-spear": { name: "ロングスピア", tier: "mid", economyValue: 50 },
  "item.greater-tonic": { name: "上級回復薬", tier: "mid", economyValue: 70 },
  "item.ward-shield": { name: "アイアンシールド", tier: "mid", economyValue: 60 },
  "item.leather-armor": { name: "レザーアーマー", tier: "early", economyValue: 35 },
  "item.chain-mail": { name: "チェインメイル", tier: "mid", economyValue: 85 },
  "item.trapweave-cloak": { name: "罠よけのマント", tier: "early", economyValue: 62 },
  "item.tower-kite-shield": { name: "タワーシールド", tier: "mid", economyValue: 82 },
  "item.silvered-mace": { name: "シルバーメイス", tier: "mid", economyValue: 96 },
  "item.mapping-scroll": { name: "地図の巻物", tier: "early", economyValue: 45 },
  "item.ember-dart": { name: "投げ針", tier: "early", economyValue: 18 },
  "item.coin-pouch": { name: "金貨袋", tier: "early", economyValue: 35 },
  "monster.ember-moth": { name: "ファイアモス", tier: "early", danger: 2, xpReward: 5, family: "beast" },
  "monster.blackshield-grub": { name: "甲殻虫", tier: "early", danger: 4, xpReward: 8, family: "beast" },
  "monster.hollow-archer": { name: "スケルトンアーチャー", tier: "early", danger: 5, xpReward: 9, family: "undead" },
  "monster.grave-leech": { name: "大ヒル", tier: "mid", danger: 5, xpReward: 11, family: "beast" },
  "monster.bramble-packling": { name: "トゲオオカミ", tier: "mid", danger: 6, xpReward: 12, family: "beast" },
  "monster.ash-warlock": { name: "ウォーロック", tier: "mid", danger: 8, xpReward: 16, family: "cult" },
  "monster.iron-reliquary-guard": { name: "アイアンゴーレム", tier: "late", danger: 10, xpReward: 24, family: "construct" },
  "monster.crypt-priest": { name: "墓所の司祭", tier: "boss", danger: 8, xpReward: 28, family: "undead" },
  "monster.blackstone-colossus": { name: "黒石の巨像", tier: "boss", danger: 11, xpReward: 44, family: "construct" },
  "monster.black-candle-warden": { name: "黒燭の番人", tier: "boss", danger: 14, xpReward: 70, family: "demon" },
  "monster.fallen-keeper": { name: "堕ちた灯守", tier: "boss", danger: 15, xpReward: 80, family: "undead" },
  "event.grave-marker": { name: "墓標", tier: "early" },
  "item.oath-knife": { name: "ダガー", tier: "early", economyValue: 28 },
  "item.guardian-draught": { name: "守りの薬", tier: "early", economyValue: 42 },
  "item.repulsion-scroll": { name: "突風の巻物", tier: "mid", economyValue: 58 },
  "item.glim-map": { name: "簡易地図", tier: "early", economyValue: 24 },
  "item.bloodmoss-salve": { name: "治療の軟膏", tier: "mid", economyValue: 46 },
  "item.unmarked-vial": { name: "謎の小瓶", tier: "early", economyValue: 26 },
  "item.sealed-prayer-strip": { name: "謎のお札", tier: "mid", economyValue: 54 },
  "event.mend-shrine": { name: "癒しの祭壇", tier: "early" },
  "event.cursed-coffer": { name: "呪われた宝箱", tier: "mid" },
  "event.warning-brazier": { name: "かがり火", tier: "early" },
  "event.dread-altar": { name: "呪いの祭壇", tier: "mid" },
  "event.furnace-control-stone": { name: "炉の制御石", tier: "late" },
  "event.seal-key": { name: "封印の鍵", tier: "mid" },
  "event.broken-armory": { name: "崩れた武器棚", tier: "mid" },
  "event.oath-echo": { name: "誓約の残響", tier: "early" },
  "event.scout-cache": { name: "レンジャーの道しるべ", tier: "early" },
  "event.lantern-font": { name: "灯火の泉", tier: "early" },
  "item.sun-sigil-blade": { name: "サンブレード", tier: "late", economyValue: 150 },
  "item.moonlit-mail": { name: "ムーンライトメイル", tier: "late", economyValue: 180 },
  "item.void-prism": { name: "虚空のプリズム", tier: "late", economyValue: 96 },
  "item.grave-sun-charm": { name: "清めのお守り", tier: "mid", economyValue: 120 },
  "item.colossus-heart": { name: "巨像のコア", tier: "late", economyValue: 150 },
  "item.black-candle-core": { name: "黒燭核", tier: "boss", economyValue: 240 },
  "event.wayfarer-merchant": { name: "旅商人", tier: "mid" },
  "event.sealed-room": { name: "封印の間", tier: "mid" },
  "event.dead-feast": { name: "亡者の食堂", tier: "mid" },
  "event.treasure-vault": { name: "宝物庫", tier: "mid" },
  "event.candle-gallery": { name: "燭台の回廊", tier: "mid" },
  "event.bone-heap": { name: "納骨部屋", tier: "mid" },
  "event.furnace-chamber": { name: "炉心室", tier: "late" },
  "trap.risk-panel": { name: "運試しの床", tier: "early", danger: 4 },
  "trap.blood-needle": { name: "針の罠", tier: "early", danger: 4 },
  "trap.venom-mist": { name: "毒霧の罠", tier: "mid", danger: 5 },
  "trap.crumbling-floor": { name: "崩れる床", tier: "mid", danger: 5 },
  "monster.brood-mother": { name: "甲殻虫の女王", tier: "boss", danger: 8, xpReward: 28, family: "beast" },
  "monster.gnawer-maw": { name: "ジャイアントワーム", tier: "boss", danger: 8, xpReward: 28, family: "beast" },
  "monster.bone-paladin": { name: "デスナイト", tier: "boss", danger: 11, xpReward: 44, family: "undead" },
  "monster.candle-eater": { name: "シャドウデーモン", tier: "boss", danger: 14, xpReward: 70, family: "demon" },
  "item.studded-club": { name: "こん棒", tier: "early", economyValue: 24 },
  "item.hatchet": { name: "ハンドアックス", tier: "early", economyValue: 30 },
  "item.ashwood-shortbow": { name: "ショートボウ", tier: "early", economyValue: 32 },
  "item.bone-javelin": { name: "ジャベリン", tier: "early", economyValue: 26 },
  "item.shadowstitch-dagger": { name: "アサシンダガー", tier: "mid", economyValue: 78 },
  "item.candle-glaive": { name: "黒燭のグレイブ", tier: "late", economyValue: 150 },
  "item.phosphor-greatbow": { name: "グレートボウ", tier: "late", economyValue: 150 },
  "item.twinfang-daggers": { name: "ツインダガー", tier: "late", economyValue: 140 },
  "item.blackiron-warhammer": { name: "ウォーハンマー", tier: "late", economyValue: 160 },
};

export function getContentName(contentId: string): string {
  return contentEntities[contentId]?.name ?? contentId;
}
