import type { ContentEntity } from "../types";

export const contentEntities: Record<string, ContentEntity> = {
  "role.oathbound": { name: "誓約の探索者", tier: "early" },
  "role.ash-scout": { name: "灰弓の斥候", tier: "early" },
  "role.lantern-priest": { name: "灯火の祈祷者", tier: "early" },
  "event.blood-inscription": { name: "血文字の碑文", tier: "early" },
  "monster.ash-rat": { name: "灰かぶり鼠", tier: "early", danger: 2, xpReward: 4, family: "beast" },
  "monster.bone-thrall": { name: "骨の従僕", tier: "early", danger: 4, xpReward: 7, family: "undead" },
  "monster.cinder-cultist": { name: "燼火の異端者", tier: "early", danger: 6, xpReward: 10, family: "cult" },
  "monster.venom-bat": { name: "毒羽の蝙蝠", tier: "early", danger: 3, xpReward: 5, family: "beast" },
  "monster.shadow-imp": { name: "影小鬼", tier: "mid", danger: 5, xpReward: 10, family: "demon" },
  "monster.moss-brute": { name: "苔むした巨躯", tier: "mid", danger: 7, xpReward: 14, family: "beast" },
  "monster.blackstone-sentinel": { name: "黒石の番兵", tier: "late", danger: 9, xpReward: 20, family: "construct" },
  "item.rusted-sword": { name: "錆びた短剣", tier: "early", economyValue: 5 },
  "item.ember-tonic": { name: "燠火の薬瓶", tier: "early", economyValue: 20 },
  "item.iron-axe": { name: "鉄の戦斧", tier: "mid", economyValue: 55 },
  "item.hunter-spear": { name: "狩人の長槍", tier: "mid", economyValue: 50 },
  "item.greater-tonic": { name: "紅蓮の大薬瓶", tier: "mid", economyValue: 70 },
  "item.ward-shield": { name: "護りの盾", tier: "mid", economyValue: 60 },
  "item.leather-armor": { name: "革の胴鎧", tier: "early", economyValue: 35 },
  "item.chain-mail": { name: "鎖かたびら", tier: "mid", economyValue: 85 },
  "item.trapweave-cloak": { name: "罠織りの外套", tier: "early", economyValue: 62 },
  "item.tower-kite-shield": { name: "塔凧の大盾", tier: "mid", economyValue: 82 },
  "item.silvered-mace": { name: "銀打ちの戦槌", tier: "mid", economyValue: 96 },
  "item.mapping-scroll": { name: "地脈図の巻物", tier: "early", economyValue: 45 },
  "item.ember-dart": { name: "燠火の投げ針", tier: "early", economyValue: 18 },
  "item.coin-pouch": { name: "古銭の袋", tier: "early", economyValue: 35 },
  "monster.ember-moth": { name: "燠羽の蛾", tier: "early", danger: 2, xpReward: 5, family: "beast" },
  "monster.blackshield-grub": { name: "黒盾の幼蟲", tier: "early", danger: 4, xpReward: 8, family: "beast" },
  "monster.hollow-archer": { name: "虚ろ弓の亡者", tier: "early", danger: 5, xpReward: 9, family: "undead" },
  "monster.grave-leech": { name: "墓所の蛭", tier: "mid", danger: 5, xpReward: 11, family: "beast" },
  "monster.bramble-packling": { name: "茨背の群れ獣", tier: "mid", danger: 6, xpReward: 12, family: "beast" },
  "monster.ash-warlock": { name: "灰燼の呪術師", tier: "mid", danger: 8, xpReward: 16, family: "cult" },
  "monster.iron-reliquary-guard": { name: "鉄聖櫃の衛士", tier: "late", danger: 10, xpReward: 24, family: "construct" },
  "monster.crypt-priest": { name: "墓所の司祭", tier: "boss", danger: 8, xpReward: 28, family: "undead" },
  "monster.blackstone-colossus": { name: "黒石巨像", tier: "boss", danger: 11, xpReward: 44, family: "construct" },
  "monster.black-candle-warden": { name: "黒燭の番人", tier: "boss", danger: 14, xpReward: 70, family: "demon" },
  "item.oath-knife": { name: "誓いの小刀", tier: "early", economyValue: 28 },
  "item.guardian-draught": { name: "護りの青薬", tier: "early", economyValue: 42 },
  "item.repulsion-scroll": { name: "退き風の巻物", tier: "mid", economyValue: 58 },
  "item.glim-map": { name: "微光の小地図", tier: "early", economyValue: 24 },
  "item.bloodmoss-salve": { name: "血苔の軟膏", tier: "mid", economyValue: 46 },
  "item.unmarked-vial": { name: "無銘の小瓶", tier: "early", economyValue: 26 },
  "item.sealed-prayer-strip": { name: "封じた祈祷札", tier: "mid", economyValue: 54 },
  "event.mend-shrine": { name: "修復の小祭壇", tier: "early" },
  "event.cursed-coffer": { name: "呪われた小箱", tier: "mid" },
  "event.warning-brazier": { name: "警告の火皿", tier: "early" },
  "event.dread-altar": { name: "忌み祭壇", tier: "mid" },
  "event.furnace-control-stone": { name: "炉心制御碑", tier: "late" },
  "event.seal-key": { name: "封印鍵", tier: "mid" },
  "event.broken-armory": { name: "崩れた武器棚", tier: "mid" },
  "event.oath-echo": { name: "誓約の残響", tier: "early" },
  "event.scout-cache": { name: "灰弓の隠し印", tier: "early" },
  "event.lantern-font": { name: "灯火の泉", tier: "early" },
  "item.sun-sigil-blade": { name: "太陽印の剣", tier: "late", economyValue: 150 },
  "item.moonlit-mail": { name: "月光鎖帷子", tier: "late", economyValue: 180 },
  "item.void-prism": { name: "虚空の角晶", tier: "late", economyValue: 96 },
  "item.grave-sun-charm": { name: "墓陽の護符", tier: "mid", economyValue: 120 },
  "item.colossus-heart": { name: "巨像の炉心片", tier: "late", economyValue: 150 },
  "item.black-candle-core": { name: "黒燭核", tier: "boss", economyValue: 240 },
  "event.wayfarer-merchant": { name: "旅商人", tier: "mid" },
  "event.sealed-room": { name: "封印部屋", tier: "mid" },
  "event.dead-feast": { name: "亡者の食堂", tier: "mid" },
  "event.treasure-vault": { name: "宝物庫", tier: "mid" },
  "event.candle-gallery": { name: "燭台廊", tier: "mid" },
  "event.bone-heap": { name: "骨塚部屋", tier: "mid" },
  "event.furnace-chamber": { name: "炉心室", tier: "late" },
  "trap.risk-panel": { name: "運命の標", tier: "early", danger: 4 },
  "trap.blood-needle": { name: "血針罠", tier: "early", danger: 4 },
  "trap.venom-mist": { name: "毒霧床", tier: "mid", danger: 5 },
  "trap.crumbling-floor": { name: "崩れ床", tier: "mid", danger: 5 },
};

export function getContentName(contentId: string): string {
  return contentEntities[contentId]?.name ?? contentId;
}
