import type { ContentEntity } from "../types";

export const contentEntities: Record<string, ContentEntity> = {
  "role.oathbound": {
    id: "role.oathbound",
    kind: "role",
    sourceRef: { game: "nethack", version: "5.0.0", file: "docs/roguelike-role-candidates.md" },
    names: { ja: "誓約の探索者", en: "Oathbound Delver" },
    description: { ja: "剣と小盾で迷宮へ踏み込む標準主人公。守り手を倒すたびに誓約報酬が増える。" },
    tags: ["starter", "melee", "survivable"],
    balance: { tier: "early", rarity: "common", utility: 8 },
    simulation: { roles: ["melee"], aiHints: ["stable-starter", "prefers-safe-fights"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["hooded-delver", "short-sword", "round-shield", "amber-lantern"],
      palette: ["hero", "dungeon"],
      promptSeed: "64x64 top-down dark fantasy hooded dungeon delver with sword, shield, amber lantern, clean silhouette",
    },
  },
  "role.ash-scout": {
    id: "role.ash-scout",
    kind: "role",
    names: { ja: "灰弓の斥候", en: "Ashen Scout" },
    description: { ja: "体力は低めだが、地図を読むたびに探索範囲と投げ針を補強できる斥候。" },
    tags: ["starter", "ranged", "scout", "fragile"],
    balance: { tier: "early", rarity: "common", utility: 8 },
    simulation: { roles: ["ranged", "skirmisher"], aiHints: ["uses-darts", "maps-early"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["hooded-scout", "spear", "ash-cloak"],
      palette: ["hero", "dungeon"],
      promptSeed: "64x64 top-down dark fantasy ash cloaked scout with spear and small map, transparent background",
    },
  },
  "role.lantern-priest": {
    id: "role.lantern-priest",
    kind: "role",
    names: { ja: "灯火の祈祷者", en: "Lantern Priest" },
    description: { ja: "攻撃力は低いが、祭壇や浄化で状態異常を護りへ変えながら粘る祈祷者。" },
    tags: ["starter", "support", "mapping", "defensive"],
    balance: { tier: "early", rarity: "common", utility: 8 },
    simulation: { roles: ["caster"], aiHints: ["maps-early", "uses-defense"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["lantern-priest", "staff", "warm-light"],
      palette: ["hero", "magic"],
      promptSeed: "64x64 top-down dark fantasy lantern priest with staff and warm light, transparent background",
    },
  },
  "terrain.floor.stone": {
    id: "terrain.floor.stone",
    kind: "terrain",
    names: { ja: "石床", en: "Stone Floor" },
    description: { ja: "黒燭の迷宮に続く冷たい石床。" },
    tags: ["floor", "walkable", "dungeon"],
    balance: {},
    simulation: { biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["cracked-stone", "low-contrast"],
      palette: ["dungeon"],
      promptSeed: "64x64 seamless top-down dark fantasy cracked stone floor tile, readable low contrast",
    },
  },
  "terrain.wall.blackstone": {
    id: "terrain.wall.blackstone",
    kind: "terrain",
    names: { ja: "黒石の壁", en: "Blackstone Wall" },
    description: { ja: "古代王国の名残を刻んだ黒い石壁。" },
    tags: ["wall", "blocks-movement", "blocks-sight", "dungeon"],
    balance: {},
    simulation: { biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["blackstone", "engraved", "solid-silhouette"],
      palette: ["dungeon"],
      promptSeed: "64x64 top-down dark fantasy blackstone wall tile with subtle ancient engravings, strong readable edge",
    },
  },
  "terrain.stairs.down": {
    id: "terrain.stairs.down",
    kind: "terrain",
    names: { ja: "下り階段", en: "Down Stairs" },
    description: { ja: "さらに暗い階層へ続く階段。" },
    tags: ["stairs", "goal", "dungeon"],
    balance: { utility: 10 },
    simulation: { aiHints: ["descend-when-safe"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["stone-stairs", "downward", "warm-rim-light"],
      palette: ["dungeon", "loot"],
      promptSeed: "64x64 top-down dark fantasy descending stone stairs with faint amber rim light, clean icon-like silhouette",
    },
  },
  "terrain.floor.crypt": {
    id: "terrain.floor.crypt",
    kind: "terrain",
    names: { ja: "墓所の石床", en: "Crypt Floor" },
    description: { ja: "骨粉と冷気が残る墓所の床。" },
    tags: ["floor", "walkable", "crypt"],
    balance: {},
    simulation: { biomes: ["crypt"] },
    modernizedSkin: {
      visualTags: ["crypt-stone", "bone-dust", "low-contrast"],
      palette: ["dungeon"],
      promptSeed: "64x64 seamless top-down dark fantasy crypt floor tile with faint bone dust",
    },
  },
  "terrain.floor.furnace": {
    id: "terrain.floor.furnace",
    kind: "terrain",
    names: { ja: "炉心遺跡の床", en: "Furnace Floor" },
    description: { ja: "消えない燠火が割れ目に残る炉心遺跡の床。" },
    tags: ["floor", "walkable", "furnace"],
    balance: {},
    simulation: { biomes: ["furnace"] },
    modernizedSkin: {
      visualTags: ["furnace-stone", "ember-cracks", "low-contrast"],
      palette: ["dungeon", "magic"],
      promptSeed: "64x64 seamless top-down dark fantasy furnace ruin floor with ember cracks",
    },
  },
  "terrain.floor.black-candle": {
    id: "terrain.floor.black-candle",
    kind: "terrain",
    names: { ja: "黒燭中枢の床", en: "Black Candle Floor" },
    description: { ja: "黒い蝋と儀式の煤が染み込んだ中枢の床。" },
    tags: ["floor", "walkable", "black-candle"],
    balance: {},
    simulation: { biomes: ["black-candle"] },
    modernizedSkin: {
      visualTags: ["ritual-stone", "black-wax", "low-contrast"],
      palette: ["dungeon", "magic"],
      promptSeed: "64x64 seamless top-down dark fantasy black candle sanctum floor",
    },
  },
  "terrain.wall.crypt": {
    id: "terrain.wall.crypt",
    kind: "terrain",
    names: { ja: "墓所の壁", en: "Crypt Wall" },
    description: { ja: "古い埋葬碑を積んだ冷たい壁。" },
    tags: ["wall", "blocks-movement", "blocks-sight", "crypt"],
    balance: {},
    simulation: { biomes: ["crypt"] },
    modernizedSkin: {
      visualTags: ["crypt-wall", "tomb-stone", "solid-silhouette"],
      palette: ["dungeon"],
      promptSeed: "64x64 top-down dark fantasy crypt wall tile with worn tomb stone",
    },
  },
  "terrain.wall.furnace": {
    id: "terrain.wall.furnace",
    kind: "terrain",
    names: { ja: "炉心遺跡の壁", en: "Furnace Wall" },
    description: { ja: "赤い割れ目を抱えた炉心遺跡の壁。" },
    tags: ["wall", "blocks-movement", "blocks-sight", "furnace"],
    balance: {},
    simulation: { biomes: ["furnace"] },
    modernizedSkin: {
      visualTags: ["furnace-wall", "ember-seams", "solid-silhouette"],
      palette: ["dungeon", "magic"],
      promptSeed: "64x64 top-down dark fantasy furnace ruin wall with ember seams",
    },
  },
  "terrain.wall.black-candle": {
    id: "terrain.wall.black-candle",
    kind: "terrain",
    names: { ja: "黒燭中枢の壁", en: "Black Candle Wall" },
    description: { ja: "黒い蝋が垂れた儀式中枢の壁。" },
    tags: ["wall", "blocks-movement", "blocks-sight", "black-candle"],
    balance: {},
    simulation: { biomes: ["black-candle"] },
    modernizedSkin: {
      visualTags: ["black-candle-wall", "wax", "solid-silhouette"],
      palette: ["dungeon", "magic"],
      promptSeed: "64x64 top-down dark fantasy black candle sanctum wall tile",
    },
  },
  "terrain.cover.blackstone": {
    id: "terrain.cover.blackstone",
    kind: "terrain",
    names: { ja: "崩れた黒石柱", en: "Broken Blackstone Pillar" },
    description: { ja: "歩いて越えられる高さの黒石柱。遠隔攻撃の射線を遮る。" },
    tags: ["cover", "walkable", "blocks-sight", "blackstone"],
    balance: {},
    simulation: { aiHints: ["breaks-ranged-line-of-sight"], biomes: ["blackstone"] },
    modernizedSkin: {
      visualTags: ["broken-pillar", "blackstone", "low-cover"],
      palette: ["dungeon"],
      promptSeed: "64x64 top-down dark fantasy broken blackstone pillar base, walkable cover terrain",
    },
  },
  "terrain.cover.crypt": {
    id: "terrain.cover.crypt",
    kind: "terrain",
    names: { ja: "石棺の遮蔽", en: "Sarcophagus Cover" },
    description: { ja: "古い石棺。身を低くすれば射線を切れる。" },
    tags: ["cover", "walkable", "blocks-sight", "crypt"],
    balance: {},
    simulation: { aiHints: ["breaks-ranged-line-of-sight"], biomes: ["crypt"] },
    modernizedSkin: {
      visualTags: ["sarcophagus", "crypt", "low-cover"],
      palette: ["dungeon"],
      promptSeed: "64x64 top-down dark fantasy sarcophagus slab, walkable cover terrain",
    },
  },
  "terrain.cover.furnace": {
    id: "terrain.cover.furnace",
    kind: "terrain",
    names: { ja: "炉心の遮熱壁", en: "Furnace Baffle" },
    description: { ja: "腰ほどの高さの遮熱壁。火花と矢を遮る。" },
    tags: ["cover", "walkable", "blocks-sight", "furnace"],
    balance: {},
    simulation: { aiHints: ["breaks-ranged-line-of-sight"], biomes: ["furnace"] },
    modernizedSkin: {
      visualTags: ["iron-baffle", "ember", "low-cover"],
      palette: ["dungeon", "magic"],
      promptSeed: "64x64 top-down dark fantasy furnace iron baffle with ember cracks, walkable cover terrain",
    },
  },
  "terrain.cover.black-candle": {
    id: "terrain.cover.black-candle",
    kind: "terrain",
    names: { ja: "黒蝋の祭壇台", en: "Black Wax Plinth" },
    description: { ja: "黒蝋に覆われた低い祭壇台。敵の射線を遮る。" },
    tags: ["cover", "walkable", "blocks-sight", "black-candle"],
    balance: {},
    simulation: { aiHints: ["breaks-ranged-line-of-sight"], biomes: ["black-candle"] },
    modernizedSkin: {
      visualTags: ["wax-plinth", "ritual", "low-cover"],
      palette: ["dungeon", "magic"],
      promptSeed: "64x64 top-down dark fantasy black wax ritual plinth, walkable cover terrain",
    },
  },
  "event.blood-inscription": {
    id: "event.blood-inscription",
    kind: "event",
    names: { ja: "血文字の碑文", en: "Blood-Written Inscription" },
    description: { ja: "探索者の記憶を刺激する、消えかけた血文字。触れると少量の経験を得る。" },
    tags: ["event", "xp", "dungeon"],
    balance: { tier: "early", rarity: "uncommon", utility: 6 },
    simulation: { aiHints: ["inspect-when-safe"], hooks: ["xp+6"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["rune", "blood", "inscription"],
      palette: ["dungeon", "magic"],
      promptSeed: "64x64 top-down dark fantasy blood-written floor inscription, transparent background, readable rune",
    },
  },
  "monster.ash-rat": {
    id: "monster.ash-rat",
    kind: "monster",
    sourceRef: { game: "nethack", version: "5.0.0", file: "docs/roguelike-enemy-candidates.md" },
    names: { ja: "灰かぶり鼠", en: "Ash Rat" },
    description: { ja: "群れからはぐれた、素早い小型の獣。" },
    tags: ["beast", "melee", "early", "small"],
    balance: { tier: "early", rarity: "common", danger: 2, xpReward: 4 },
    simulation: { family: "beast", roles: ["skirmisher"], aiHints: ["low-threat", "close-to-attack"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["ash-fur", "red-eyes", "small-beast"],
      palette: ["monster", "dungeon"],
      promptSeed: "64x64 top-down dark fantasy ash-gray dungeon rat monster, red eyes, clean sprite silhouette",
    },
  },
  "monster.bone-thrall": {
    id: "monster.bone-thrall",
    kind: "monster",
    sourceRef: { game: "nethack", version: "5.0.0", file: "docs/roguelike-enemy-candidates.md" },
    names: { ja: "骨の従僕", en: "Bone Thrall" },
    description: { ja: "朽ちた兵士の骨に残留魔力がまとわりついたもの。" },
    tags: ["undead", "melee", "early"],
    balance: { tier: "early", rarity: "uncommon", danger: 4, xpReward: 7 },
    simulation: { family: "undead", roles: ["melee"], aiHints: ["steady-pursuit"], biomes: ["dungeon", "crypt"] },
    modernizedSkin: {
      visualTags: ["skeleton", "rusted-blade", "blue-ember"],
      palette: ["monster", "magic"],
      promptSeed: "64x64 top-down dark fantasy skeletal thrall with rusted blade and faint blue ember, readable sprite",
    },
  },
  "monster.cinder-cultist": {
    id: "monster.cinder-cultist",
    kind: "monster",
    sourceRef: { game: "nethack", version: "5.0.0", file: "docs/roguelike-enemy-candidates.md" },
    names: { ja: "燼火の異端者", en: "Cinder Cultist" },
    description: { ja: "黒燭を崇める低位の術師。距離を取って火花を放つ。" },
    tags: ["cult", "caster", "early", "ranged-threat"],
    balance: { tier: "early", rarity: "rare", danger: 6, xpReward: 10 },
    simulation: { family: "cult", roles: ["caster", "ranged"], aiHints: ["avoid-melee", "backs-away-when-cornered", "ranged-chip"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["tattered-robe", "ember-hand", "masked-cultist"],
      palette: ["monster", "magic"],
      promptSeed: "64x64 top-down dark fantasy masked cinder cultist in tattered robe holding ember magic, clean silhouette",
    },
  },
  "monster.venom-bat": {
    id: "monster.venom-bat",
    kind: "monster",
    names: { ja: "毒羽の蝙蝠", en: "Venom Bat" },
    description: { ja: "暗がりから滑るように近づく毒羽の小型獣。" },
    tags: ["beast", "flying", "skirmisher", "early"],
    balance: { tier: "early", rarity: "uncommon", danger: 3, xpReward: 5 },
    simulation: { family: "beast", roles: ["skirmisher"], aiHints: ["fast-flanker"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["bat", "venom", "winged"],
      palette: ["monster"],
      promptSeed: "64x64 top-down dark fantasy venom bat monster, transparent background, readable sprite",
    },
  },
  "monster.shadow-imp": {
    id: "monster.shadow-imp",
    kind: "monster",
    names: { ja: "影小鬼", en: "Shadow Imp" },
    description: { ja: "影の隙間を跳ね回る、ずる賢い小鬼。" },
    tags: ["demon", "skirmisher", "mid"],
    balance: { tier: "mid", rarity: "uncommon", danger: 5, xpReward: 10 },
    simulation: { family: "demon", roles: ["skirmisher"], aiHints: ["opportunistic"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["imp", "shadow", "horned"],
      palette: ["monster", "magic"],
      promptSeed: "64x64 top-down dark fantasy shadow imp, transparent background, readable sprite",
    },
  },
  "monster.moss-brute": {
    id: "monster.moss-brute",
    kind: "monster",
    names: { ja: "苔むした巨躯", en: "Moss Brute" },
    description: { ja: "迷宮の湿気を吸った、遅いが頑丈な怪物。" },
    tags: ["beast", "melee", "mid", "durable"],
    balance: { tier: "mid", rarity: "rare", danger: 7, xpReward: 14 },
    simulation: { family: "beast", roles: ["melee"], aiHints: ["slow-heavy"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["moss", "brute", "heavy"],
      palette: ["monster"],
      promptSeed: "64x64 top-down dark fantasy moss brute monster, transparent background, readable sprite",
    },
  },
  "monster.blackstone-sentinel": {
    id: "monster.blackstone-sentinel",
    kind: "monster",
    names: { ja: "黒石の番兵", en: "Blackstone Sentinel" },
    description: { ja: "古代の炉心で動く石造りの番兵。" },
    tags: ["construct", "melee", "late", "durable"],
    balance: { tier: "late", rarity: "rare", danger: 9, xpReward: 20 },
    simulation: { family: "construct", roles: ["melee"], aiHints: ["elite-guard"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["construct", "blackstone", "ember-core"],
      palette: ["monster", "magic"],
      promptSeed: "64x64 top-down dark fantasy blackstone sentinel construct, transparent background, readable sprite",
    },
  },
  "item.rusted-sword": {
    id: "item.rusted-sword",
    kind: "item",
    sourceRef: { game: "nethack", version: "5.0.0", file: "docs/roguelike-item-equipment-candidates.md" },
    names: { ja: "錆びた短剣", en: "Rusted Shortblade" },
    description: { ja: "頼りないが、素手よりはましな刃。" },
    tags: ["weapon", "melee", "early"],
    balance: { tier: "early", rarity: "common", utility: 3, economyValue: 5 },
    simulation: { aiHints: ["equip-if-stronger"], hooks: ["attack+1"] },
    modernizedSkin: {
      visualTags: ["shortblade", "rust", "low-tier-loot"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy rusted short sword item icon, transparent background, clean outline",
    },
  },
  "item.ember-tonic": {
    id: "item.ember-tonic",
    kind: "item",
    sourceRef: { game: "nethack", version: "5.0.0", file: "docs/roguelike-item-equipment-candidates.md" },
    names: { ja: "燠火の薬瓶", en: "Ember Tonic" },
    description: { ja: "小さな傷を塞ぐ、序盤向けの温かな赤い薬。" },
    tags: ["potion", "healing", "consumable", "early"],
    balance: { tier: "early", rarity: "common", utility: 7, economyValue: 20 },
    simulation: { aiHints: ["use-when-hp-low"], hooks: ["heal+10"] },
    modernizedSkin: {
      visualTags: ["red-vial", "warm-glow", "consumable"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy red healing potion vial with warm ember glow, transparent background",
    },
  },
  "item.iron-axe": {
    id: "item.iron-axe",
    kind: "item",
    names: { ja: "鉄の戦斧", en: "Iron Axe" },
    description: { ja: "重いが頼れる迷宮用の斧。" },
    tags: ["weapon", "melee", "mid"],
    balance: { tier: "mid", rarity: "uncommon", utility: 8, economyValue: 55 },
    simulation: { aiHints: ["equip-if-stronger"], hooks: ["attack+4"] },
    modernizedSkin: {
      visualTags: ["axe", "iron", "weapon"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy iron battle axe, transparent background",
    },
  },
  "item.hunter-spear": {
    id: "item.hunter-spear",
    kind: "item",
    names: { ja: "狩人の長槍", en: "Hunter Spear" },
    description: { ja: "間合いを取りやすい、迷宮探索者向けの長槍。遠隔攻撃も少し受け流しやすい。" },
    tags: ["weapon", "melee", "mid"],
    balance: { tier: "mid", rarity: "uncommon", utility: 7, economyValue: 50 },
    simulation: { aiHints: ["equip-if-stronger"], hooks: ["attack+3", "ranged-defense+1"] },
    modernizedSkin: {
      visualTags: ["spear", "hunter", "weapon"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy hunter spear, transparent background",
    },
  },
  "item.greater-tonic": {
    id: "item.greater-tonic",
    kind: "item",
    names: { ja: "紅蓮の大薬瓶", en: "Greater Crimson Tonic" },
    description: { ja: "状態異常は治せないが、深い傷を一気に塞ぐ濃い赤の薬。" },
    tags: ["potion", "healing", "consumable", "mid"],
    balance: { tier: "mid", rarity: "uncommon", utility: 12, economyValue: 70 },
    simulation: { aiHints: ["use-when-hp-low"], hooks: ["heal+30"] },
    modernizedSkin: {
      visualTags: ["red-flask", "healing", "greater"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy greater red healing flask, transparent background",
    },
  },
  "item.ward-shield": {
    id: "item.ward-shield",
    kind: "item",
    names: { ja: "護りの盾", en: "Ward Shield" },
    description: { ja: "黒燭の印が刻まれた防御用の盾。矢を受け止めやすいが、足元への反応は鈍る。" },
    tags: ["shield", "armor", "defense", "mid"],
    balance: { tier: "mid", rarity: "uncommon", utility: 9, economyValue: 60 },
    simulation: { aiHints: ["equip-if-defensive"], hooks: ["defense+2", "ranged-defense+2", "trap-avoid-3"] },
    modernizedSkin: {
      visualTags: ["shield", "ward", "defense"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy ward shield, transparent background",
    },
  },
  "item.leather-armor": {
    id: "item.leather-armor",
    kind: "item",
    names: { ja: "革の胴鎧", en: "Leather Armor" },
    description: { ja: "軽く動きやすい、探索者向けの防具。罠を踏み抜く直前に身をかわしやすい。" },
    tags: ["armor", "defense", "early"],
    balance: { tier: "early", rarity: "common", utility: 5, economyValue: 35 },
    simulation: { aiHints: ["equip-if-unarmored"], hooks: ["defense+1", "trap-avoid+12"] },
    modernizedSkin: {
      visualTags: ["leather-armor", "defense", "loot"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy leather armor item icon, transparent background",
    },
  },
  "item.chain-mail": {
    id: "item.chain-mail",
    kind: "item",
    names: { ja: "鎖かたびら", en: "Chain Mail" },
    description: { ja: "重いが確かな防御力を持つ鎖編みの鎧。矢には強いが、罠回避は落ちる。" },
    tags: ["armor", "defense", "mid"],
    balance: { tier: "mid", rarity: "rare", utility: 10, economyValue: 85 },
    simulation: { aiHints: ["equip-if-defensive"], hooks: ["defense+3", "ranged-defense+1", "trap-avoid-8"] },
    modernizedSkin: {
      visualTags: ["chain-mail", "armor", "defense"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy chain mail armor item icon, transparent background",
    },
  },
  "item.trapweave-cloak": {
    id: "item.trapweave-cloak",
    kind: "item",
    names: { ja: "罠織りの外套", en: "Trapweave Cloak" },
    description: { ja: "薄い護符糸を縫い込んだ外套。防御は軽いが、床の異変を察しやすい。" },
    tags: ["armor", "defense", "trap", "early"],
    balance: { tier: "early", rarity: "uncommon", utility: 8, economyValue: 62 },
    simulation: { aiHints: ["equip-if-trap-heavy"], hooks: ["defense+1", "trap-avoid+22"] },
    modernizedSkin: {
      visualTags: ["cloak", "trap-sense", "light-armor"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy dark cloak with tiny ward threads, transparent background",
    },
  },
  "item.tower-kite-shield": {
    id: "item.tower-kite-shield",
    kind: "item",
    names: { ja: "塔凧の大盾", en: "Tower Kite Shield" },
    description: { ja: "矢と呪火を受ける大盾。遠隔攻撃には強いが、足元への反応はかなり鈍る。" },
    tags: ["shield", "armor", "ranged-defense", "mid"],
    balance: { tier: "mid", rarity: "uncommon", utility: 10, economyValue: 82 },
    simulation: { aiHints: ["equip-against-ranged"], hooks: ["defense+1", "ranged-defense+3", "trap-avoid-8"] },
    modernizedSkin: {
      visualTags: ["large-shield", "anti-arrow", "heavy"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy tall kite shield with black candle scars, transparent background",
    },
  },
  "item.silvered-mace": {
    id: "item.silvered-mace",
    kind: "item",
    names: { ja: "銀打ちの戦槌", en: "Silvered Mace" },
    description: { ja: "不死と悪魔の骨を砕くために銀を打ち込んだ戦槌。基礎火力は控えめだが相手を選ぶ。" },
    tags: ["weapon", "melee", "silver", "mid"],
    balance: { tier: "mid", rarity: "rare", utility: 11, economyValue: 96 },
    simulation: { aiHints: ["equip-against-undead-demon"], hooks: ["attack+3", "bonus-vs-undead-demon"] },
    modernizedSkin: {
      visualTags: ["mace", "silver", "anti-undead"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy silvered mace weapon icon, transparent background",
    },
  },
  "item.mapping-scroll": {
    id: "item.mapping-scroll",
    kind: "item",
    names: { ja: "地脈図の巻物", en: "Scroll of Mapping" },
    description: { ja: "現在階の地形を一気に把握する古い地図。" },
    tags: ["scroll", "mapping", "utility"],
    balance: { tier: "early", rarity: "uncommon", utility: 10, economyValue: 45 },
    simulation: { aiHints: ["use-to-reveal-floor"], hooks: ["map-floor"] },
    modernizedSkin: {
      visualTags: ["scroll", "map", "utility"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy map scroll, transparent background",
    },
  },
  "item.ember-dart": {
    id: "item.ember-dart",
    kind: "item",
    names: { ja: "燠火の投げ針", en: "Ember Dart" },
    description: { ja: "近くの敵へ投げつける、熱を帯びた小さな投げ針。" },
    tags: ["throwing", "consumable", "ranged", "early"],
    balance: { tier: "early", rarity: "uncommon", utility: 8, economyValue: 18 },
    simulation: { aiHints: ["throw-at-visible-enemy"], hooks: ["ranged-damage+7"] },
    modernizedSkin: {
      visualTags: ["dart", "ember", "throwing"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy ember throwing dart item icon, transparent background",
    },
  },
  "item.coin-pouch": {
    id: "item.coin-pouch",
    kind: "item",
    names: { ja: "古銭の袋", en: "Coin Pouch" },
    description: { ja: "古い金貨が詰まった小袋。拾うと所持金に加わる。" },
    tags: ["treasure", "gold"],
    balance: { tier: "early", rarity: "common", utility: 2, economyValue: 35 },
    simulation: { aiHints: ["collect-treasure"], hooks: ["score"] },
    modernizedSkin: {
      visualTags: ["coin-pouch", "treasure"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy coin pouch, transparent background",
    },
  },
  "monster.ember-moth": {
    id: "monster.ember-moth",
    kind: "monster",
    names: { ja: "燠羽の蛾", en: "Ember Moth" },
    description: { ja: "火の粉をまきながら素早く近づく、小さな飛行獣。" },
    tags: ["beast", "flying", "skirmisher", "early"],
    balance: { tier: "early", rarity: "common", danger: 2, xpReward: 5 },
    simulation: { family: "beast", roles: ["skirmisher"], aiHints: ["fast-low-hp"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["ember", "moth", "winged"],
      palette: ["monster", "magic"],
      promptSeed: "64x64 top-down dark fantasy ember moth monster, transparent background, readable sprite",
    },
  },
  "monster.blackshield-grub": {
    id: "monster.blackshield-grub",
    kind: "monster",
    names: { ja: "黒盾の幼蟲", en: "Blackshield Grub" },
    description: { ja: "硬い殻で通路を塞ぐ、遅いがしぶとい幼蟲。" },
    tags: ["beast", "melee", "durable", "early"],
    balance: { tier: "early", rarity: "uncommon", danger: 4, xpReward: 8 },
    simulation: { family: "beast", roles: ["melee"], aiHints: ["durable-blocker"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["armored-grub", "black-shell"],
      palette: ["monster"],
      promptSeed: "64x64 top-down dark fantasy armored black grub monster, transparent background",
    },
  },
  "monster.hollow-archer": {
    id: "monster.hollow-archer",
    kind: "monster",
    names: { ja: "虚ろ弓の亡者", en: "Hollow Archer" },
    description: { ja: "近づかれる前に骨の矢を放つ、痩せた弓兵の亡者。" },
    tags: ["undead", "ranged", "early"],
    balance: { tier: "early", rarity: "uncommon", danger: 5, xpReward: 9 },
    simulation: { family: "undead", roles: ["ranged"], aiHints: ["ranged-chip", "backs-away-when-cornered"], biomes: ["dungeon", "crypt"] },
    modernizedSkin: {
      visualTags: ["undead", "archer", "bow"],
      palette: ["monster"],
      promptSeed: "64x64 top-down dark fantasy hollow undead archer, transparent background",
    },
  },
  "monster.grave-leech": {
    id: "monster.grave-leech",
    kind: "monster",
    names: { ja: "墓所の蛭", en: "Grave Leech" },
    description: { ja: "噛み跡から出血を残す、青白い地這いの怪物。" },
    tags: ["beast", "melee", "bleed", "mid"],
    balance: { tier: "mid", rarity: "uncommon", danger: 5, xpReward: 11 },
    simulation: { family: "beast", roles: ["melee"], aiHints: ["causes-bleed", "life-steal-on-hit"], biomes: ["dungeon", "crypt"] },
    modernizedSkin: {
      visualTags: ["leech", "pale", "bleed"],
      palette: ["monster"],
      promptSeed: "64x64 top-down dark fantasy grave leech monster, transparent background",
    },
  },
  "monster.bramble-packling": {
    id: "monster.bramble-packling",
    kind: "monster",
    names: { ja: "茨背の群れ獣", en: "Bramble Packling" },
    description: { ja: "茨を背負い、仲間の影に紛れて突進する群れ獣。" },
    tags: ["beast", "melee", "pack", "mid"],
    balance: { tier: "mid", rarity: "uncommon", danger: 6, xpReward: 12 },
    simulation: { family: "beast", roles: ["skirmisher"], aiHints: ["pack-pressure"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["bramble", "pack-beast"],
      palette: ["monster"],
      promptSeed: "64x64 top-down dark fantasy bramble-backed pack beast, transparent background",
    },
  },
  "monster.ash-warlock": {
    id: "monster.ash-warlock",
    kind: "monster",
    names: { ja: "灰燼の呪術師", en: "Ash Warlock" },
    description: { ja: "灰の呪いを遠くから流し込む、危険な中位術師。" },
    tags: ["cult", "caster", "ranged-threat", "mid"],
    balance: { tier: "mid", rarity: "rare", danger: 8, xpReward: 16 },
    simulation: { family: "cult", roles: ["caster", "ranged"], aiHints: ["ranged-poison", "backs-away-when-cornered", "summons-minions"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["warlock", "ash", "caster"],
      palette: ["monster", "magic"],
      promptSeed: "64x64 top-down dark fantasy ash warlock, transparent background",
    },
  },
  "monster.iron-reliquary-guard": {
    id: "monster.iron-reliquary-guard",
    kind: "monster",
    names: { ja: "鉄聖櫃の衛士", en: "Iron Reliquary Guard" },
    description: { ja: "炉心を抱えた重装の守護者。遅いが非常に硬い。" },
    tags: ["construct", "elite", "durable", "late"],
    balance: { tier: "late", rarity: "rare", danger: 10, xpReward: 24 },
    simulation: { family: "construct", roles: ["melee"], aiHints: ["elite-guard"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["reliquary", "iron", "ember-core"],
      palette: ["monster", "magic"],
      promptSeed: "64x64 top-down dark fantasy iron reliquary guard construct, transparent background",
    },
  },
  "monster.crypt-priest": {
    id: "monster.crypt-priest",
    kind: "monster",
    names: { ja: "墓所の司祭", en: "Crypt Priest" },
    description: { ja: "地下三階の階段を封じる、骨と灰を従えた中ボス。" },
    tags: ["undead", "caster", "boss", "crypt"],
    balance: { tier: "boss", rarity: "special", danger: 8, xpReward: 28 },
    simulation: { family: "undead", roles: ["caster", "boss"], aiHints: ["floor-gatekeeper"], biomes: ["crypt"] },
    modernizedSkin: {
      visualTags: ["crypt-priest", "bone-mask", "boss"],
      palette: ["monster", "magic"],
      promptSeed: "64x64 top-down dark fantasy crypt priest boss with bone mask, transparent background",
    },
  },
  "monster.blackstone-colossus": {
    id: "monster.blackstone-colossus",
    kind: "monster",
    names: { ja: "黒石巨像", en: "Blackstone Colossus" },
    description: { ja: "地下六階の通路を揺らす、炉心を抱えた巨大な石像。" },
    tags: ["construct", "durable", "boss", "furnace"],
    balance: { tier: "boss", rarity: "special", danger: 11, xpReward: 44 },
    simulation: { family: "construct", roles: ["melee", "boss"], aiHints: ["floor-gatekeeper", "durable"], biomes: ["furnace"] },
    modernizedSkin: {
      visualTags: ["blackstone-colossus", "ember-core", "boss"],
      palette: ["monster", "magic"],
      promptSeed: "64x64 top-down dark fantasy blackstone colossus boss with ember core, transparent background",
    },
  },
  "monster.black-candle-warden": {
    id: "monster.black-candle-warden",
    kind: "monster",
    names: { ja: "黒燭の番人", en: "Black Candle Warden" },
    description: { ja: "第十層の中枢を守る、黒い燭火をまとった最終守護者。" },
    tags: ["demon", "cult", "boss", "black-candle"],
    balance: { tier: "boss", rarity: "special", danger: 14, xpReward: 70 },
    simulation: { family: "demon", roles: ["caster", "boss"], aiHints: ["final-gatekeeper"], biomes: ["black-candle"] },
    modernizedSkin: {
      visualTags: ["black-candle-warden", "dark-flame", "boss"],
      palette: ["monster", "magic"],
      promptSeed: "64x64 top-down dark fantasy black candle warden final boss with dark flame, transparent background",
    },
  },
  "item.oath-knife": {
    id: "item.oath-knife",
    kind: "item",
    names: { ja: "誓いの小刀", en: "Oath Knife" },
    description: { ja: "扱いやすく、序盤の護身に向いた短い刃。足元の危険へ反応しやすい。" },
    tags: ["weapon", "melee", "early"],
    balance: { tier: "early", rarity: "uncommon", utility: 5, economyValue: 28 },
    simulation: { aiHints: ["equip-if-stronger"], hooks: ["attack+2", "trap-avoid+4"] },
    modernizedSkin: {
      visualTags: ["knife", "oath", "weapon"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy oath knife item icon, transparent background",
    },
  },
  "item.guardian-draught": {
    id: "item.guardian-draught",
    kind: "item",
    names: { ja: "護りの青薬", en: "Guardian Draught" },
    description: { ja: "短時間だけ防御を高める青い薬液。" },
    tags: ["potion", "defense", "consumable", "early"],
    balance: { tier: "early", rarity: "uncommon", utility: 9, economyValue: 42 },
    simulation: { aiHints: ["use-before-dangerous-fight"], hooks: ["temporary-defense+3"] },
    modernizedSkin: {
      visualTags: ["blue-vial", "shield", "defense"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy blue defensive potion with shield glow, transparent background",
    },
  },
  "item.repulsion-scroll": {
    id: "item.repulsion-scroll",
    kind: "item",
    names: { ja: "退き風の巻物", en: "Scroll of Repulsion" },
    description: { ja: "視界内の敵を押し戻す、短い猶予を作る巻物。" },
    tags: ["scroll", "control", "consumable", "mid"],
    balance: { tier: "mid", rarity: "uncommon", utility: 10, economyValue: 58 },
    simulation: { aiHints: ["use-when-surrounded"], hooks: ["push-visible-enemies"] },
    modernizedSkin: {
      visualTags: ["scroll", "wind", "control"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy repulsion scroll with wind spiral, transparent background",
    },
  },
  "item.glim-map": {
    id: "item.glim-map",
    kind: "item",
    names: { ja: "微光の小地図", en: "Glim Map" },
    description: { ja: "近くの部屋と通路だけを照らす、折り畳みの小地図。" },
    tags: ["map", "utility", "consumable", "early"],
    balance: { tier: "early", rarity: "common", utility: 6, economyValue: 24 },
    simulation: { aiHints: ["use-to-reveal-nearby"], hooks: ["map-nearby"] },
    modernizedSkin: {
      visualTags: ["glowing-map", "utility"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy glowing folded map, transparent background",
    },
  },
  "item.bloodmoss-salve": {
    id: "item.bloodmoss-salve",
    kind: "item",
    names: { ja: "血苔の軟膏", en: "Bloodmoss Salve" },
    description: { ja: "毒と出血を抑え、傷もある程度塞ぐ薬壺。" },
    tags: ["salve", "healing", "cure", "consumable", "mid"],
    balance: { tier: "mid", rarity: "uncommon", utility: 9, economyValue: 46 },
    simulation: { aiHints: ["cure-conditions"], hooks: ["cure-bleed-poison", "heal+22"] },
    modernizedSkin: {
      visualTags: ["salve", "bloodmoss", "cure"],
      palette: ["loot"],
      promptSeed: "64x64 top-down dark fantasy bloodmoss salve jar, transparent background",
    },
  },
  "item.unmarked-vial": {
    id: "item.unmarked-vial",
    kind: "item",
    names: { ja: "無銘の小瓶", en: "Unmarked Vial" },
    description: { ja: "中身が読めない黒硝子の小瓶。薬にも毒にも見える。" },
    tags: ["potion", "mystery", "consumable", "early"],
    balance: { tier: "early", rarity: "uncommon", utility: 7, economyValue: 26 },
    simulation: { aiHints: ["test-when-safe", "use-as-last-resort"], hooks: ["unknown-effect", "heal-or-harm"] },
    modernizedSkin: {
      visualTags: ["black-vial", "unknown", "risk-reward"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy unmarked black glass vial with faint amber seal, transparent background",
    },
  },
  "item.sealed-prayer-strip": {
    id: "item.sealed-prayer-strip",
    kind: "item",
    names: { ja: "封じた祈祷札", en: "Sealed Prayer Strip" },
    description: { ja: "古い祈りが封じられた札。灯火の祈祷者なら危うい文言を読み替えられる。" },
    tags: ["scroll", "mystery", "prayer", "consumable", "mid"],
    balance: { tier: "mid", rarity: "uncommon", utility: 9, economyValue: 54 },
    simulation: { aiHints: ["test-when-safe", "priest-safer-use"], hooks: ["unknown-effect", "guard-or-reveal-or-curse"] },
    modernizedSkin: {
      visualTags: ["sealed-paper-strip", "prayer", "unknown"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy sealed prayer paper strip with wax mark, transparent background",
    },
  },
  "event.mend-shrine": {
    id: "event.mend-shrine",
    kind: "event",
    names: { ja: "修復の小祭壇", en: "Mend Shrine" },
    description: { ja: "触れると傷と状態異常を少し癒やす、ひび割れた祭壇。" },
    tags: ["event", "healing", "shrine"],
    balance: { tier: "early", rarity: "uncommon", utility: 9 },
    simulation: { aiHints: ["inspect-when-injured"], hooks: ["heal+14", "cure-conditions"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["altar", "healing", "warm-light"],
      palette: ["magic", "loot"],
      promptSeed: "64x64 top-down dark fantasy cracked healing shrine, transparent background",
    },
  },
  "event.cursed-coffer": {
    id: "event.cursed-coffer",
    kind: "event",
    names: { ja: "呪われた小箱", en: "Cursed Coffer" },
    description: { ja: "金貨を抱えるが、開く者へ代償を求める小箱。" },
    tags: ["event", "treasure", "risk"],
    balance: { tier: "mid", rarity: "rare", utility: 8 },
    simulation: { aiHints: ["risk-reward"], hooks: ["gold", "bleed"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["cursed-chest", "violet-glow"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy cursed coffer, transparent background",
    },
  },
  "event.warning-brazier": {
    id: "event.warning-brazier",
    kind: "event",
    names: { ja: "警告の火皿", en: "Warning Brazier" },
    description: { ja: "周囲の危険を短く照らす、古い警告灯。" },
    tags: ["event", "reveal", "warning"],
    balance: { tier: "early", rarity: "uncommon", utility: 7 },
    simulation: { aiHints: ["inspect-to-reveal"], hooks: ["map-nearby"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["brazier", "warning", "amber-flame"],
      palette: ["magic", "dungeon"],
      promptSeed: "64x64 top-down dark fantasy warning brazier, transparent background",
    },
  },
  "event.dread-altar": {
    id: "event.dread-altar",
    kind: "event",
    names: { ja: "忌み祭壇", en: "Dread Altar" },
    description: { ja: "触れると血の気配を床に走らせ、隠れた罠の一部を暴くが、出血の代償を伴う祭壇。" },
    tags: ["event", "altar", "trap-reveal", "risk"],
    balance: { tier: "mid", rarity: "rare", utility: 10 },
    simulation: { aiHints: ["inspect-when-safe", "reveals-traps"], hooks: ["reveal-traps", "bleed"], biomes: ["dungeon", "crypt"] },
    modernizedSkin: {
      visualTags: ["altar", "blood", "warning"],
      palette: ["magic", "danger"],
      promptSeed: "64x64 top-down dark fantasy blood altar marker, transparent background",
    },
  },
  "event.furnace-control-stone": {
    id: "event.furnace-control-stone",
    kind: "event",
    names: { ja: "炉心制御碑", en: "Furnace Control Stone" },
    description: { ja: "砕けば炉心遺跡以降の敵の火勢を弱めるが、その場で大きな音を立てる制御碑。" },
    tags: ["event", "furnace", "late-game", "enemy-weaken"],
    balance: { tier: "late", rarity: "rare", utility: 12 },
    simulation: { aiHints: ["inspect-before-late-floors"], hooks: ["weaken-late-enemies"], biomes: ["furnace"] },
    modernizedSkin: {
      visualTags: ["obelisk", "ember", "control-stone"],
      palette: ["magic", "dungeon"],
      promptSeed: "64x64 top-down dark fantasy ember control obelisk, transparent background",
    },
  },
  "event.seal-key": {
    id: "event.seal-key",
    kind: "event",
    names: { ja: "封印鍵", en: "Seal Key" },
    description: { ja: "拾うと次の守り手の報酬封印が緩み、ボス撃破時の追加報酬が増える小さな鍵。" },
    tags: ["event", "key", "boss-reward", "optional"],
    balance: { tier: "mid", rarity: "rare", utility: 11 },
    simulation: { aiHints: ["collect-for-boss-reward"], hooks: ["boss-reward-bonus"], biomes: ["dungeon", "furnace"] },
    modernizedSkin: {
      visualTags: ["key", "seal", "relic"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy sealed key relic, transparent background",
    },
  },
  "event.broken-armory": {
    id: "event.broken-armory",
    kind: "event",
    names: { ja: "崩れた武器棚", en: "Broken Armory" },
    description: { ja: "古い武器が残る、壊れかけた棚。" },
    tags: ["event", "weapon", "loot"],
    balance: { tier: "mid", rarity: "uncommon", utility: 8 },
    simulation: { aiHints: ["inspect-for-weapon"], hooks: ["weapon-loot"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["broken-rack", "weapons", "loot"],
      palette: ["loot", "dungeon"],
      promptSeed: "64x64 top-down dark fantasy broken weapon rack, transparent background",
    },
  },
  "event.oath-echo": {
    id: "event.oath-echo",
    kind: "event",
    names: { ja: "誓約の残響", en: "Oath Echo" },
    description: { ja: "守り手へ挑んだ探索者の誓いが残る黒石の印。誓約の探索者なら強く応える。" },
    tags: ["event", "role", "oathbound", "reward"],
    balance: { tier: "early", rarity: "uncommon", utility: 9 },
    simulation: { aiHints: ["inspect-when-safe"], hooks: ["role-oathbound-reward"] },
    modernizedSkin: {
      visualTags: ["oath-rune", "blackstone", "role-event"],
      palette: ["magic"],
      promptSeed: "64x64 top-down dark fantasy blackstone oath rune marker, transparent background",
    },
  },
  "event.scout-cache": {
    id: "event.scout-cache",
    kind: "event",
    names: { ja: "灰弓の隠し印", en: "Ashbow Cache Mark" },
    description: { ja: "斥候だけが読める灰色の印。道筋と備蓄の位置を示している。" },
    tags: ["event", "role", "scout", "map", "supply"],
    balance: { tier: "early", rarity: "uncommon", utility: 10 },
    simulation: { aiHints: ["inspect-when-safe"], hooks: ["role-scout-map-supply"] },
    modernizedSkin: {
      visualTags: ["ash-mark", "hidden-cache", "role-event"],
      palette: ["magic"],
      promptSeed: "64x64 top-down dark fantasy ash scout cache mark on floor, transparent background",
    },
  },
  "event.lantern-font": {
    id: "event.lantern-font",
    kind: "event",
    names: { ja: "灯火の泉", en: "Lantern Font" },
    description: { ja: "濁った水面の下に小さな灯が揺れる泉。灯火の祈祷者なら穢れを護りに変えられる。" },
    tags: ["event", "role", "priest", "healing", "cleanse"],
    balance: { tier: "early", rarity: "uncommon", utility: 10 },
    simulation: { aiHints: ["inspect-when-hurt-or-cursed"], hooks: ["role-priest-cleanse"] },
    modernizedSkin: {
      visualTags: ["lantern-font", "holy-water", "role-event"],
      palette: ["magic"],
      promptSeed: "64x64 top-down dark fantasy lantern-lit cleansing font, transparent background",
    },
  },
  "item.sun-sigil-blade": {
    id: "item.sun-sigil-blade",
    kind: "item",
    names: { ja: "太陽印の剣", en: "Sun-Sigil Blade" },
    description: { ja: "不死者、悪魔、異端者に追加ダメージを与える上級の聖印剣。" },
    tags: ["weapon", "melee", "special", "late"],
    balance: { tier: "late", rarity: "rare", utility: 14, economyValue: 150 },
    simulation: { aiHints: ["equip-if-stronger", "anti-undead-cult"], hooks: ["attack+5", "bonus-vs-undead-demon-cult"] },
    modernizedSkin: {
      visualTags: ["sun", "blade", "holy"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy sun sigil blade, transparent background",
    },
  },
  "item.moonlit-mail": {
    id: "item.moonlit-mail",
    kind: "item",
    names: { ja: "月光鎖帷子", en: "Moonlit Mail" },
    description: { ja: "高い防御に加えて、一定ターンごとに小さく傷を塞ぐ上級鎧。重さで罠回避は少し落ちる。" },
    tags: ["armor", "defense", "healing", "special", "late"],
    balance: { tier: "late", rarity: "rare", utility: 15, economyValue: 180 },
    simulation: { aiHints: ["equip-if-defensive", "regenerates"], hooks: ["defense+4", "ranged-defense+1", "trap-avoid-5", "regen-every-10-turns"] },
    modernizedSkin: {
      visualTags: ["moon", "mail", "regeneration"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy moonlit chain mail, transparent background",
    },
  },
  "item.void-prism": {
    id: "item.void-prism",
    kind: "item",
    names: { ja: "虚空の角晶", en: "Void Prism" },
    description: { ja: "周囲を広く暴き、見えている敵を押し戻す希少な使い切り遺物。" },
    tags: ["relic", "control", "mapping", "consumable", "special", "late"],
    balance: { tier: "late", rarity: "rare", utility: 13, economyValue: 96 },
    simulation: { aiHints: ["use-in-danger", "reveal-and-control"], hooks: ["map-wide", "push-visible-enemies"] },
    modernizedSkin: {
      visualTags: ["void", "prism", "relic"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy void prism charm, transparent background",
    },
  },
  "item.grave-sun-charm": {
    id: "item.grave-sun-charm",
    kind: "item",
    names: { ja: "墓陽の護符", en: "Grave-Sun Charm" },
    description: { ja: "墓所の司祭が残す護符。毒と出血を払い、傷を塞ぎ、短い護りを与える。" },
    tags: ["relic", "healing", "cure", "boss-reward", "consumable"],
    balance: { tier: "mid", rarity: "special", utility: 13, economyValue: 120 },
    simulation: { aiHints: ["use-when-hurt-or-conditioned"], hooks: ["cure-bleed-poison", "heal+24", "temporary-defense"] },
    modernizedSkin: {
      visualTags: ["sun-charm", "bone", "relic"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy grave sun charm relic, transparent background",
    },
  },
  "item.colossus-heart": {
    id: "item.colossus-heart",
    kind: "item",
    names: { ja: "巨像の炉心片", en: "Colossus Heart Shard" },
    description: { ja: "黒石巨像の炉心片。長めの護りを与える使い切り遺物。" },
    tags: ["relic", "defense", "boss-reward", "consumable"],
    balance: { tier: "late", rarity: "special", utility: 14, economyValue: 150 },
    simulation: { aiHints: ["use-before-dangerous-fight"], hooks: ["temporary-defense+3"] },
    modernizedSkin: {
      visualTags: ["ember-core", "stone-heart", "relic"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy ember colossus heart shard relic, transparent background",
    },
  },
  "item.black-candle-core": {
    id: "item.black-candle-core",
    kind: "item",
    names: { ja: "黒燭核", en: "Black Candle Core" },
    description: { ja: "黒燭の番人が落とす中枢核。広く照らし、敵を遠ざけ、傷を少し押し戻す。" },
    tags: ["relic", "control", "mapping", "healing", "boss-reward", "consumable"],
    balance: { tier: "boss", rarity: "special", utility: 18, economyValue: 240 },
    simulation: { aiHints: ["use-in-final-danger"], hooks: ["map-wide", "push-visible-enemies", "heal+20"] },
    modernizedSkin: {
      visualTags: ["black-candle-core", "dark-flame", "relic"],
      palette: ["loot", "magic"],
      promptSeed: "64x64 top-down dark fantasy black candle core relic with dark flame, transparent background",
    },
  },
  "event.wayfarer-merchant": {
    id: "event.wayfarer-merchant",
    kind: "event",
    names: { ja: "旅商人", en: "Wayfarer Merchant" },
    description: { ja: "迷宮の浅くない階層で、回復、解毒、装備、地図を選んで頼める灯持ちの旅商人。" },
    tags: ["event", "merchant", "gold", "service"],
    balance: { tier: "mid", rarity: "rare", utility: 12 },
    simulation: { aiHints: ["spend-gold-on-supplies"], hooks: ["shop"], biomes: ["dungeon"] },
    modernizedSkin: {
      visualTags: ["merchant", "lantern", "backpack"],
      palette: ["loot", "dungeon"],
      promptSeed: "64x64 top-down dark fantasy hooded dungeon merchant, transparent background",
    },
  },
  "event.sealed-room": {
    id: "event.sealed-room",
    kind: "event",
    names: { ja: "封印部屋", en: "Sealed Room" },
    description: { ja: "古い封印を破ると、守り手と備蓄が同時に現れる小部屋。" },
    tags: ["event", "room", "combat", "reward"],
    balance: { tier: "mid", rarity: "rare", utility: 10 },
    simulation: { aiHints: ["inspect-when-safe"], hooks: ["room-encounter"], biomes: ["dungeon", "furnace"] },
    modernizedSkin: {
      visualTags: ["sealed-door", "rune", "room-marker"],
      palette: ["dungeon", "magic"],
      promptSeed: "64x64 top-down dark fantasy sealed room marker with runic lock, transparent background",
    },
  },
  "event.dead-feast": {
    id: "event.dead-feast",
    kind: "event",
    names: { ja: "亡者の食堂", en: "Dead Feast Hall" },
    description: { ja: "朽ちた食卓の周りに亡者が集まり、薬や金貨も残る部屋。" },
    tags: ["event", "room", "undead", "risk-reward"],
    balance: { tier: "mid", rarity: "uncommon", utility: 9 },
    simulation: { aiHints: ["inspect-when-safe"], hooks: ["room-encounter"], biomes: ["crypt"] },
    modernizedSkin: {
      visualTags: ["dead-feast", "table", "bones"],
      palette: ["dungeon"],
      promptSeed: "64x64 top-down dark fantasy dead feast table room marker, transparent background",
    },
  },
  "event.treasure-vault": {
    id: "event.treasure-vault",
    kind: "event",
    names: { ja: "宝物庫", en: "Treasure Vault" },
    description: { ja: "価値ある品と罠が同居する、狭い宝物庫。" },
    tags: ["event", "room", "treasure", "trap"],
    balance: { tier: "mid", rarity: "rare", utility: 12 },
    simulation: { aiHints: ["risk-reward"], hooks: ["room-encounter", "gold"], biomes: ["dungeon", "furnace"] },
    modernizedSkin: {
      visualTags: ["vault", "treasure", "locked"],
      palette: ["loot", "dungeon"],
      promptSeed: "64x64 top-down dark fantasy treasure vault marker, transparent background",
    },
  },
  "event.candle-gallery": {
    id: "event.candle-gallery",
    kind: "event",
    names: { ja: "燭台廊", en: "Candle Gallery" },
    description: { ja: "壁沿いに黒い燭台が並ぶ部屋。火が移ると道筋と待ち伏せが同時に浮かぶ。" },
    tags: ["event", "room", "reveal", "ambush"],
    balance: { tier: "mid", rarity: "uncommon", utility: 10 },
    simulation: { aiHints: ["reveals-room-with-ambush"], hooks: ["room-reveal", "monster-guard", "map-reward"] },
    modernizedSkin: {
      visualTags: ["candle-gallery", "room-marker", "ambush"],
      palette: ["magic"],
      promptSeed: "64x64 top-down dark fantasy candle gallery room marker, transparent background",
    },
  },
  "event.bone-heap": {
    id: "event.bone-heap",
    kind: "event",
    names: { ja: "骨塚部屋", en: "Bone Heap Room" },
    description: { ja: "物資が骨の下に埋もれた部屋。崩すと亡者も起きる。" },
    tags: ["event", "room", "undead", "risk-reward"],
    balance: { tier: "mid", rarity: "uncommon", utility: 10 },
    simulation: { aiHints: ["loot-with-undead-risk"], hooks: ["room-undead", "loot"] },
    modernizedSkin: {
      visualTags: ["bone-heap", "room-marker", "loot"],
      palette: ["monster", "loot"],
      promptSeed: "64x64 top-down dark fantasy bone heap room marker with buried supplies, transparent background",
    },
  },
  "event.furnace-chamber": {
    id: "event.furnace-chamber",
    kind: "event",
    names: { ja: "炉心室", en: "Furnace Chamber" },
    description: { ja: "熱で歪んだ鉄板と崩れ床が混じる部屋。遮蔽を使って守り手と戦う。" },
    tags: ["event", "room", "furnace", "cover", "trap"],
    balance: { tier: "late", rarity: "rare", utility: 12 },
    simulation: { aiHints: ["cover-and-trap-room"], hooks: ["adds-cover", "adds-trap", "monster-guard"] },
    modernizedSkin: {
      visualTags: ["furnace-room", "cover", "trap"],
      palette: ["magic", "terrain"],
      promptSeed: "64x64 top-down dark fantasy furnace chamber room marker with ember iron plates, transparent background",
    },
  },
  "trap.risk-panel": {
    id: "trap.risk-panel",
    kind: "trap",
    names: { ja: "運命の標", en: "Fate Sigil" },
    description: { ja: "踏むまで祝福か災いか分からない、淡く揺れる疑問の標。" },
    tags: ["trap", "risk-reward", "unknown"],
    balance: { tier: "early", rarity: "uncommon", danger: 4, utility: 6 },
    simulation: { aiHints: ["step-when-desperate-or-stuck"], hooks: ["random-risk-reward"], biomes: ["dungeon", "crypt", "furnace"] },
    modernizedSkin: {
      visualTags: ["question-sigil", "unknown", "floor-marker"],
      palette: ["dungeon", "magic"],
      promptSeed: "64x64 top-down dark fantasy glowing question sigil floor marker, transparent background",
    },
  },
  "trap.blood-needle": {
    id: "trap.blood-needle",
    kind: "trap",
    names: { ja: "血針罠", en: "Blood Needle Trap" },
    description: { ja: "床石の隙間から黒い針が跳ね上がり、出血を残す罠。" },
    tags: ["trap", "bleed", "hidden-danger"],
    balance: { tier: "early", rarity: "uncommon", danger: 4 },
    simulation: { aiHints: ["avoid-if-known"], hooks: ["bleed"], biomes: ["dungeon", "crypt"] },
    modernizedSkin: {
      visualTags: ["needle-trap", "blood", "floor-marker"],
      palette: ["dungeon", "danger"],
      promptSeed: "64x64 top-down dark fantasy blood needle floor trap, transparent background, readable marker",
    },
  },
  "trap.venom-mist": {
    id: "trap.venom-mist",
    kind: "trap",
    names: { ja: "毒霧床", en: "Venom Mist Floor" },
    description: { ja: "踏むと緑黒い毒霧が吹き出す危険な床。" },
    tags: ["trap", "poison", "floor"],
    balance: { tier: "mid", rarity: "uncommon", danger: 5 },
    simulation: { aiHints: ["avoid-if-known"], hooks: ["poison"], biomes: ["crypt"] },
    modernizedSkin: {
      visualTags: ["venom-mist", "green-haze", "floor-marker"],
      palette: ["dungeon", "danger"],
      promptSeed: "64x64 top-down dark fantasy venom mist floor trap, transparent background, readable marker",
    },
  },
  "trap.crumbling-floor": {
    id: "trap.crumbling-floor",
    kind: "trap",
    names: { ja: "崩れ床", en: "Crumbling Floor" },
    description: { ja: "足を置くと割れて落石を呼ぶ、不安定な床。" },
    tags: ["trap", "impact", "floor"],
    balance: { tier: "mid", rarity: "uncommon", danger: 5 },
    simulation: { aiHints: ["avoid-if-known"], hooks: ["impact-damage"], biomes: ["furnace"] },
    modernizedSkin: {
      visualTags: ["cracked-floor", "collapse", "floor-marker"],
      palette: ["dungeon", "danger"],
      promptSeed: "64x64 top-down dark fantasy crumbling floor trap, transparent background, readable marker",
    },
  },
};

export function getContentName(contentId: string): string {
  return contentEntities[contentId]?.names.ja ?? contentId;
}
